export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireAuth } from '@/lib/auth/middleware'
import { prisma } from '@/lib/db/postgres'
import { getCurrentProjectId } from '@/lib/tenant/isolation'

/**
 * Generate auth code files from policies and providers
 * and save them directly to the workspace
 */
export async function POST(request: NextRequest) {
  try {
    await requireAuth(request)
    const projectId = await getCurrentProjectId(request)
    
    if (!projectId) {
      return NextResponse.json({ error: 'No project selected' }, { status: 400 })
    }
    
    // Fetch current auth configuration
    const [providers, policies] = await Promise.all([
      prisma.authProvider.findMany({ where: { enabled: true } }),
      // @ts-ignore - Prisma client will include this after restart
      prisma.authPolicy.findMany({ where: { enabled: true } }),
    ])
    
    // Generate code based on configuration
    const files = generateAuthCode(providers, policies)
    
    // Save files to workspace
    for (const file of files) {
      // @ts-ignore - Prisma client will include this after restart
      await prisma.workspaceFile.upsert({
        where: {
          projectId_path: {
            projectId,
            path: file.path
          }
        },
        update: {
          content: file.content,
          description: file.description,
          category: 'auth',
          language: 'typescript'
        },
        create: {
          projectId,
          path: file.path,
          content: file.content,
          description: file.description,
          category: 'auth',
          language: 'typescript'
        }
      })
    }
    
    return NextResponse.json({ 
      success: true,
      files,
      message: `${files.length} auth files saved to workspace`
    })
  } catch (error) {
    console.error('Generate auth code error:', error)
    return NextResponse.json(
      { error: 'Failed to generate auth code' },
      { status: 500 }
    )
  }
}

function generateAuthCode(providers: any[], policies: any[]) {
  const files = []
  
  // 1. Generate auth.config.ts
  files.push({
    path: 'src/auth/auth.config.ts',
    content: generateAuthConfig(providers, policies),
    description: 'Auth configuration based on your policies'
  })
  
  // 2. Generate auth.middleware.ts
  files.push({
    path: 'src/auth/auth.middleware.ts',
    content: generateAuthMiddleware(policies),
    description: 'JWT authentication middleware'
  })
  
  // 3. Generate auth.routes.ts
  files.push({
    path: 'src/auth/auth.routes.ts',
    content: generateAuthRoutes(providers, policies),
    description: 'Auth endpoints (login, signup, logout)'
  })
  
  // 4. Generate user.model.ts
  files.push({
    path: 'src/auth/user.model.ts',
    content: generateUserModel(policies),
    description: 'User database schema'
  })
  
  return files
}

function generateAuthConfig(providers: any[], policies: any[]) {
  const passwordPolicy = policies.find(p => p.name.includes('Password'))
  const sessionPolicy = policies.find(p => p.name.includes('Session'))
  const emailPolicy = policies.find(p => p.name.includes('Email'))
  
  return `// Generated by backenly AI from Auth Policies
// You fully own this code - customize as needed

export const authConfig = {
  // Enabled authentication providers
  providers: {
    email: ${providers.some(p => p.name === 'email')},
    google: ${providers.some(p => p.name === 'google')},
    github: ${providers.some(p => p.name === 'github')},
    microsoft: ${providers.some(p => p.name === 'microsoft')},
  },
  
  // Password policy (from: ${passwordPolicy?.name || 'default'})
  password: {
    minLength: 8,
    requireUppercase: true,
    requireLowercase: true,
    requireNumbers: true,
    requireSpecialChars: false,
  },
  
  // Session configuration (from: ${sessionPolicy?.name || 'default'})
  session: {
    strategy: 'jwt' as const,
    maxAge: 7 * 24 * 60 * 60, // 7 days
    updateAge: 24 * 60 * 60, // 1 day
  },
  
  // JWT configuration
  jwt: {
    secret: process.env.JWT_SECRET ?? (() => { throw new Error('JWT_SECRET environment variable is required') })(),
    expiresIn: '7d',
  },
  
  // Email verification (from: ${emailPolicy?.name || 'default'})
  emailVerification: {
    required: ${emailPolicy ? 'true' : 'false'},
    expiresIn: 24 * 60 * 60, // 24 hours
  },
}
`
}

function generateAuthMiddleware(policies: any[]) {
  return `// Generated by backenly AI from Auth Policies
// You fully own this code - customize as needed

import { Request, Response, NextFunction } from 'express'
import jwt from 'jsonwebtoken'
import { authConfig } from './auth.config'

export interface AuthRequest extends Request {
  user?: {
    id: string
    email: string
    role: string
  }
}

/**
 * JWT Authentication Middleware
 */
export function authenticate(req: AuthRequest, res: Response, next: NextFunction) {
  try {
    const token = req.headers.authorization?.replace('Bearer ', '')
    
    if (!token) {
      return res.status(401).json({ error: 'Authentication required' })
    }
    
    const decoded = jwt.verify(token, authConfig.jwt.secret) as any
    req.user = decoded
    
    next()
  } catch (error) {
    return res.status(401).json({ error: 'Invalid or expired token' })
  }
}

/**
 * Role-based authorization guard
 */
export function authorize(...roles: string[]) {
  return (req: AuthRequest, res: Response, next: NextFunction) => {
    if (!req.user) {
      return res.status(401).json({ error: 'Authentication required' })
    }
    
    if (roles.length && !roles.includes(req.user.role)) {
      return res.status(403).json({ error: 'Insufficient permissions' })
    }
    
    next()
  }
}

/**
 * Email verification guard
 */
export function requireEmailVerification(req: AuthRequest, res: Response, next: NextFunction) {
  if (!authConfig.emailVerification.required) {
    return next()
  }
  
  // Check if user email is verified (implement based on your user model)
  // This is a placeholder - customize based on your needs
  next()
}
`
}

function generateAuthRoutes(providers: any[], policies: any[]) {
  const hasEmail = providers.some(p => p.name === 'email')
  const hasGoogle = providers.some(p => p.name === 'google')
  const hasGithub = providers.some(p => p.name === 'github')
  
  return `// Generated by backenly AI from Auth Policies
// You fully own this code - customize as needed

import { Router, Request, Response } from 'express'
import bcrypt from 'bcrypt'
import jwt from 'jsonwebtoken'
import { authConfig } from './auth.config'
import { authenticate } from './auth.middleware'

const router = Router()

${hasEmail ? `
/**
 * Email/Password Signup
 */
router.post('/signup', async (req: Request, res: Response) => {
  try {
    const { email, password } = req.body
    
    // Validate password against policy
    if (password.length < authConfig.password.minLength) {
      return res.status(400).json({ 
        error: \`Password must be at least \${authConfig.password.minLength} characters\`
      })
    }
    
    // Hash password — 12 rounds (OWASP 2026 floor). Was 10.
    const hashedPassword = await bcrypt.hash(password, 12)
    
    // Create user (implement database logic)
    // const user = await db.user.create({ email, password: hashedPassword })
    
    // Generate JWT
    const token = jwt.sign(
      { id: 'user-id', email, role: 'user' },
      authConfig.jwt.secret,
      { expiresIn: authConfig.jwt.expiresIn }
    )
    
    res.json({ token, user: { email } })
  } catch (error) {
    res.status(500).json({ error: 'Signup failed' })
  }
})

/**
 * Email/Password Login
 */
router.post('/login', async (req: Request, res: Response) => {
  try {
    const { email, password } = req.body
    
    // Find user (implement database logic)
    // const user = await db.user.findUnique({ where: { email } })
    
    // Verify password
    // const valid = await bcrypt.compare(password, user.password)
    
    // Generate JWT
    const token = jwt.sign(
      { id: 'user-id', email, role: 'user' },
      authConfig.jwt.secret,
      { expiresIn: authConfig.jwt.expiresIn }
    )
    
    res.json({ token, user: { email } })
  } catch (error) {
    res.status(401).json({ error: 'Invalid credentials' })
  }
})
` : ''}

${hasGoogle || hasGithub ? `
/**
 * OAuth callback handler
 * Implement OAuth flow based on your provider
 */
router.get('/callback/:provider', async (req: Request, res: Response) => {
  const { provider } = req.params
  // Implement OAuth callback logic
  res.json({ message: \`\${provider} OAuth callback\` })
})
` : ''}

/**
 * Get current user
 */
router.get('/me', authenticate, (req: any, res: Response) => {
  res.json({ user: req.user })
})

/**
 * Logout
 */
router.post('/logout', authenticate, (req: Request, res: Response) => {
  // Implement token invalidation if using refresh tokens
  res.json({ message: 'Logged out successfully' })
})

export default router
`
}

function generateUserModel(policies: any[]) {
  const emailVerification = policies.find(p => p.name.includes('Email'))
  const twoFactor = policies.find(p => p.name.includes('Two-Factor'))
  
  return `// Generated by backenly AI from Auth Policies
// You fully own this code - customize as needed

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

/**
 * User Model (Prisma Schema)
 * Add this to your schema.prisma file:
 */
export const userSchema = \`
model User {
  id            String    @id @default(uuid())
  email         String    @unique
  password      String
  ${emailVerification ? 'emailVerified Boolean   @default(false)' : ''}
  ${emailVerification ? 'verificationToken String?' : ''}
  ${twoFactor ? 'twoFactorEnabled Boolean   @default(false)' : ''}
  ${twoFactor ? 'twoFactorSecret String?' : ''}
  role          String    @default("user")
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  lastLogin     DateTime?
  
  @@map("users")
}
\`

// User type
export interface User {
  id: string
  email: string
  ${emailVerification ? 'emailVerified: boolean' : ''}
  ${twoFactor ? 'twoFactorEnabled: boolean' : ''}
  role: string
  createdAt: Date
  updatedAt: Date
  lastLogin?: Date
}

// User operations
export const userService = {
  async findByEmail(email: string) {
    return prisma.user.findUnique({ where: { email } })
  },
  
  async create(data: { email: string; password: string }) {
    return prisma.user.create({ data })
  },
  
  async updateLastLogin(id: string) {
    return prisma.user.update({
      where: { id },
      data: { lastLogin: new Date() }
    })
  }
}
`
}
