/**
 * An assembled Prisma workspace: schema plus the canonical migrations, in a
 * directory built for one run.
 *
 * The repository's `prisma/migrations/` is deliberately NOT the canonical
 * history. It is gitignored, and on developer machines it still holds the legacy
 * corpus that builds 50 of 119 tables. Pointing `prisma migrate` at it would
 * apply a history nobody wants, and deleting it would destroy the only local
 * copy of evidence.
 *
 * So the canonical history lives at `prisma/migrations-canonical/`, tracked, and
 * every Prisma invocation runs against a directory assembled from it. Prisma
 * resolves `migrations/` relative to the schema file it is given, so an
 * assembled directory is all `migrate deploy` needs — and the legacy corpus can
 * never be picked up by accident, here or in an image.
 */

import { cpSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

export const CANONICAL_DIR = join('prisma', 'migrations-canonical')
export const MIGRATION_LOCK = '# Please do not edit this file manually\nprovider = "postgresql"\n'

export interface AssembledWorkspace {
  /** Directory holding schema.prisma and migrations/. */
  dir: string
  schemaPath: string
  migrationsDir: string
  migrations: string[]
  dispose: () => void
}

/**
 * Copy schema.prisma and the canonical migrations into a fresh directory.
 *
 * `extra` adds migrations that exist only for a rehearsal, so a disposable
 * forward-migration fixture never has to be written into the repository.
 */
export function assembleMigrationWorkspace(
  root: string,
  extra: Array<{ id: string; sql: string }> = [],
  options: { only?: string[] } = {},
): AssembledWorkspace {
  const canonical = join(root, CANONICAL_DIR)
  if (!existsSync(canonical)) throw new Error(`${CANONICAL_DIR} does not exist; generate the baseline first`)

  const dir = mkdtempSync(join(tmpdir(), 'backenly-migrations-'))
  const migrationsDir = join(dir, 'migrations')
  mkdirSync(migrationsDir, { recursive: true })

  // `only` exists for the baseline rehearsal, which must reproduce the state
  // staging was in: the canonical schema present and ONLY the baseline known.
  const ids = readdirSync(canonical, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .filter(id => !options.only || options.only.includes(id))
    .sort()
  for (const id of ids) cpSync(join(canonical, id), join(migrationsDir, id), { recursive: true })

  const lockSource = join(canonical, 'migration_lock.toml')
  writeFileSync(
    join(migrationsDir, 'migration_lock.toml'),
    existsSync(lockSource) ? readFileSync(lockSource, 'utf8') : MIGRATION_LOCK,
  )

  for (const { id, sql } of extra) {
    mkdirSync(join(migrationsDir, id), { recursive: true })
    writeFileSync(join(migrationsDir, id, 'migration.sql'), sql)
  }

  const schemaPath = join(dir, 'schema.prisma')
  writeFileSync(schemaPath, readFileSync(join(root, 'prisma', 'schema.prisma'), 'utf8'))

  return {
    dir,
    schemaPath,
    migrationsDir,
    migrations: [...ids, ...extra.map(e => e.id)].sort(),
    dispose: () => rmSync(dir, { recursive: true, force: true }),
  }
}
