-- Enable measured query latency.
--
-- Backenly's `measured_slow_queries_are_indexed` invariant reads
-- pg_stat_statements to find the columns this database actually spends
-- milliseconds filtering on, verifies them against the catalog, and proposes an
-- index only for what survives. It is the one detector that reasons from
-- MEASUREMENT rather than from schema shape.
--
-- Without the extension that detector cannot run. Backenly reports the
-- invariant as UNCHECKED rather than satisfied (see
-- lib/autonomy/platform-capabilities.ts), so nothing lies about it — but the
-- capability is simply absent until this runs.
--
-- The library itself is preloaded via `shared_preload_libraries` in
-- docker-compose.dev.yml; that part requires a server restart and cannot be
-- done from SQL. This file only creates the extension, which is why both halves
-- have to exist.
--
-- Runs once, on first initialisation of an empty data directory. On an existing
-- database, run this statement by hand after adding the preload setting.
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- Enable measured index bloat.
--
-- `indexes_are_not_mostly_empty_space` reads avg_leaf_density from
-- pgstatindex(). That number is in no statistics view, and the well-known
-- "index bloat estimate" queries derive it from column widths and row counts —
-- approximations that go wrong on wide text keys, partial indexes and
-- non-default fillfactor, which is most of what anyone actually asks about.
--
-- Unlike pg_stat_statements this needs no preload and no restart, so it is
-- safe to add to an existing database with exactly this statement.
CREATE EXTENSION IF NOT EXISTS pgstattuple;
