/**
 * OPENAPI 3.0 SPEC GENERATOR
 * ==========================
 * Generates a complete OpenAPI 3.0.3 specification from a project's
 * ApiDefinition records and workspace schema.
 *
 * The spec can be:
 *  - Downloaded as openapi.json from the Connect tab
 *  - Imported into Postman, Insomnia, Swagger UI
 *  - Used to generate client SDKs
 */

import { prisma } from '@/lib/db/prisma'

// ─── Type helpers ─────────────────────────────────────────────────────────────

function pgTypeToJsonSchema(pgType: string): Record<string, any> {
  const t = pgType.toUpperCase()
  if (t === 'TEXT' || t === 'VARCHAR' || t === 'UUID') return { type: 'string' }
  if (t === 'INTEGER' || t === 'INT' || t === 'BIGINT') return { type: 'integer' }
  if (t.startsWith('DECIMAL') || t.startsWith('NUMERIC') || t === 'FLOAT' || t === 'DOUBLE PRECISION')
    return { type: 'number' }
  if (t === 'BOOLEAN') return { type: 'boolean' }
  if (t === 'TIMESTAMP' || t === 'DATE' || t === 'TIMESTAMPTZ')
    return { type: 'string', format: 'date-time' }
  if (t === 'JSONB' || t === 'JSON') return { type: 'object' }
  if (t === 'TEXT[]' || t === 'VARCHAR[]') return { type: 'array', items: { type: 'string' } }
  return { type: 'string' } // fallback
}

function sanitize(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]/g, '_')
}

function titleCase(s: string): string {
  return s.replace(/_./g, m => m[1].toUpperCase()).replace(/^./, m => m.toUpperCase())
}

// ─── Main generator ───────────────────────────────────────────────────────────

export async function generateOpenApiSpec(projectId: string, baseUrl?: string): Promise<Record<string, any>> {
  // Fetch all API definitions + tables + AI functions
  const [apiDefs, aiFunctions, project] = await Promise.all([
    // The CATALOG, not ApiDefinition. That table has had no create path since
    // the PostgREST cutover, so this spec came back with zero paths on every
    // project built after it - an OpenAPI document describing a backend as
    // having no endpoints while it served traffic. Columns come from
    // information_schema via getTableSchema, which is also what the runtime
    // resolves against, so the spec cannot drift from what is actually served.
    (async () => {
      const { listExposedTables, getTableSchema } = await import('@/lib/mcp/schema-introspection')
      const exposed = await listExposedTables(projectId).catch(() => [] as Array<{ name: string }>)
      return Promise.all(
        exposed.map(async t => ({
          table: {
            name: t.name,
            schema: await getTableSchema(projectId, t.name).catch(() => null),
          },
        })),
      )
    })(),
    prisma.aiFunction.findMany({
      where: { projectId, status: 'active' },
      orderBy: { createdAt: 'asc' },
    }),
    prisma.project.findFirst({
      where: { id: projectId },
      select: { name: true, description: true, apiUrlProd: true, apiUrlDev: true },
    }),
  ])

  const serverUrl = baseUrl
    || project?.apiUrlProd
    || project?.apiUrlDev
    || `https://api.backenly.com`

  const spec: Record<string, any> = {
    openapi: '3.0.3',
    info: {
      title: `${project?.name || 'My Backend'} API`,
      description: project?.description
        || 'Auto-generated by Backenly — Autonomous Backend Platform',
      version: '1.0.0',
      contact: { url: 'https://backenly.com' },
    },
    servers: [
      { url: `${serverUrl}/api/v1/${projectId}`, description: 'Production' },
    ],
    security: [{ BearerAuth: [] }, { ApiKeyAuth: [] }],
    components: {
      securitySchemes: {
        BearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'End-user JWT obtained from POST /auth/signin',
        },
        ApiKeyAuth: {
          type: 'apiKey',
          in: 'header',
          name: 'x-api-key',
          description: 'Project API key from the IAM tab',
        },
      },
      schemas: {},
      responses: {
        Unauthorized: {
          description: 'Authentication required',
          content: { 'application/json': { schema: { '$ref': '#/components/schemas/Error' } } },
        },
        RateLimited: {
          description: 'Rate limit exceeded',
          content: { 'application/json': { schema: { '$ref': '#/components/schemas/Error' } } },
        },
        NotFound: {
          description: 'Resource not found',
          content: { 'application/json': { schema: { '$ref': '#/components/schemas/Error' } } },
        },
      },
    },
    paths: {},
    tags: [],
  }

  spec.components.schemas.Error = {
    type: 'object',
    properties: {
      error: { type: 'string' },
      code: { type: 'string' },
    },
    required: ['error'],
  }

  // ── Standard CRUD API definitions ───────────────────────────────────────────
  for (const def of apiDefs) {
    if (!def.table || !def.table.schema) continue

    const tableName = def.table.name
    const tag = titleCase(tableName)
    const schemaName = sanitize(titleCase(tableName))
    const basePath = `/db/${tableName}`

    spec.tags.push({ name: tag, description: `Operations on the ${tableName} table` })

    // Build schema from table columns
    // getTableSchema returns live information_schema columns:
    // { name, type, nullable, default, primaryKey, maxLength }. `required` is
    // derived from nullability rather than a stored flag.
    const tableSchema = (def.table.schema as any) || {}
    const columns: any[] = (tableSchema.columns || []).map((c: any) => ({
      name: c.name,
      type: c.type,
      required: c.nullable === false && c.default == null && !c.primaryKey,
    }))
    const properties: Record<string, any> = {}
    const required: string[] = []

    for (const col of columns) {
      if (col.name === 'id') {
        properties.id = { type: 'string', format: 'uuid', readOnly: true }
        continue
      }
      if (col.name === 'created_at' || col.name === 'updated_at') {
        properties[col.name] = { type: 'string', format: 'date-time', readOnly: true }
        continue
      }
      properties[col.name] = pgTypeToJsonSchema(col.type || 'TEXT')
      if (col.required && col.name !== 'id') required.push(col.name)
    }

    // Add standard fields if no columns found
    if (Object.keys(properties).length === 0) {
      properties.id = { type: 'string', format: 'uuid', readOnly: true }
      properties.created_at = { type: 'string', format: 'date-time', readOnly: true }
      properties.updated_at = { type: 'string', format: 'date-time', readOnly: true }
    }

    spec.components.schemas[schemaName] = { type: 'object', properties, required: required.length > 0 ? required : undefined }
    spec.components.schemas[`${schemaName}Input`] = {
      type: 'object',
      properties: Object.fromEntries(
        Object.entries(properties).filter(([k]) => k !== 'id' && k !== 'created_at' && k !== 'updated_at')
      ),
    }

    // Every exposed table serves the same CRUD set: the /db/* route registers
    // GET/POST/PUT/PATCH/DELETE and PostgREST resolves the table per request.
    // These used to be gated on a stored `endpoints` array, which is why the
    // spec listed nothing once that table stopped being written.
    //
    // `/search` is deliberately absent: handleViaPostgrest refuses sub-resource
    // paths, so advertising it would document an endpoint that 404s.
    const hasSearch = false

    // GET /db/{table} — list
    if (true) {
      spec.paths[basePath] = spec.paths[basePath] || {}
      spec.paths[basePath].get = {
        tags: [tag],
        summary: `List ${tableName}`,
        operationId: `list${schemaName}`,
        parameters: [
          { name: 'limit', in: 'query', schema: { type: 'integer', default: 50, maximum: 1000 } },
          { name: 'offset', in: 'query', schema: { type: 'integer', default: 0 } },
          { name: 'orderBy', in: 'query', schema: { type: 'string' }, description: 'Column name to sort by' },
          { name: 'order', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'], default: 'asc' } },
        ],
        responses: {
          '200': {
            description: 'List of records',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    data: { type: 'array', items: { '$ref': `#/components/schemas/${schemaName}` } },
                    count: { type: 'integer' },
                  },
                },
              },
            },
          },
          '401': { '$ref': '#/components/responses/Unauthorized' },
        },
      }

      // POST /db/{table} — create
      if (true) {
        spec.paths[basePath].post = {
          tags: [tag],
          summary: `Create ${tableName.slice(0, -1) || tableName}`,
          operationId: `create${schemaName}`,
          requestBody: {
            required: true,
            content: { 'application/json': { schema: { '$ref': `#/components/schemas/${schemaName}Input` } } },
          },
          responses: {
            '201': {
              description: 'Created record',
              content: { 'application/json': { schema: { '$ref': `#/components/schemas/${schemaName}` } } },
            },
            '401': { '$ref': '#/components/responses/Unauthorized' },
          },
        }
      }
    }

    // GET /db/{table}/:id, PUT, DELETE
    const byIdPath = `${basePath}/{id}`
    spec.paths[byIdPath] = spec.paths[byIdPath] || {}
    const idParam = { name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }

    if (true) {
      spec.paths[byIdPath].get = {
        tags: [tag],
        summary: `Get ${tableName.slice(0, -1) || tableName} by ID`,
        operationId: `get${schemaName}ById`,
        parameters: [idParam],
        responses: {
          '200': { description: 'Record', content: { 'application/json': { schema: { '$ref': `#/components/schemas/${schemaName}` } } } },
          '401': { '$ref': '#/components/responses/Unauthorized' },
          '404': { '$ref': '#/components/responses/NotFound' },
        },
      }
    }
    if (true) {
      spec.paths[byIdPath].put = {
        tags: [tag],
        summary: `Update ${tableName.slice(0, -1) || tableName}`,
        operationId: `update${schemaName}`,
        parameters: [idParam],
        requestBody: { required: true, content: { 'application/json': { schema: { '$ref': `#/components/schemas/${schemaName}Input` } } } },
        responses: {
          '200': { description: 'Updated record', content: { 'application/json': { schema: { '$ref': `#/components/schemas/${schemaName}` } } } },
          '401': { '$ref': '#/components/responses/Unauthorized' },
          '404': { '$ref': '#/components/responses/NotFound' },
        },
      }
    }
    if (true) {
      spec.paths[byIdPath].delete = {
        tags: [tag],
        summary: `Delete ${tableName.slice(0, -1) || tableName}`,
        operationId: `delete${schemaName}`,
        parameters: [idParam],
        responses: {
          '204': { description: 'Deleted' },
          '401': { '$ref': '#/components/responses/Unauthorized' },
          '404': { '$ref': '#/components/responses/NotFound' },
        },
      }
    }

    // GET /db/{table}/search — full-text search
    if (hasSearch) {
      const searchPath = `${basePath}/search`
      spec.paths[searchPath] = {
        get: {
          tags: [tag],
          summary: `Search ${tableName}`,
          operationId: `search${schemaName}`,
          parameters: [
            { name: 'q', in: 'query', required: true, schema: { type: 'string' }, description: 'Full-text search query' },
            { name: 'limit', in: 'query', schema: { type: 'integer', default: 20 } },
          ],
          responses: {
            '200': {
              description: 'Search results',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: {
                      data: { type: 'array', items: { '$ref': `#/components/schemas/${schemaName}` } },
                      count: { type: 'integer' },
                    },
                  },
                },
              },
            },
          },
        },
      }
    }
  }

  // ── Auth endpoints ───────────────────────────────────────────────────────────
  spec.tags.push({ name: 'Auth', description: 'End-user authentication' })
  spec.paths['/auth/signup'] = {
    post: {
      tags: ['Auth'], summary: 'Sign up', operationId: 'signUp', security: [],
      requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { email: { type: 'string' }, password: { type: 'string' }, name: { type: 'string' } }, required: ['email', 'password'] } } } },
      responses: { '201': { description: 'User created', content: { 'application/json': { schema: { type: 'object', properties: { token: { type: 'string' }, user: { type: 'object' } } } } } } },
    },
  }
  spec.paths['/auth/signin'] = {
    post: {
      tags: ['Auth'], summary: 'Sign in', operationId: 'signIn', security: [],
      requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { email: { type: 'string' }, password: { type: 'string' } }, required: ['email', 'password'] } } } },
      responses: { '200': { description: 'JWT token', content: { 'application/json': { schema: { type: 'object', properties: { token: { type: 'string' }, user: { type: 'object' } } } } } } },
    },
  }

  // ── AI Functions as endpoints ─────────────────────────────────────────────
  const validAiFns = aiFunctions.filter(fn => fn.name && fn.name.trim() !== '')
  if (validAiFns.length > 0) {
    spec.tags.push({ name: 'Functions', description: 'AI-generated serverless functions' })
  }
  for (const fn of validAiFns) {
    const VALID_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
    const firstToken = (fn.triggerTable || '').split(' ')[0]?.toUpperCase()
    const method = VALID_METHODS.includes(firstToken) ? firstToken.toLowerCase() : 'post'

    spec.paths[`/fn/${fn.name}`] = {
      [method]: {
        tags: ['Functions'],
        summary: fn.description,
        operationId: `fn_${sanitize(fn.name)}`,
        responses: { '200': { description: 'Function result', content: { 'application/json': { schema: { type: 'object' } } } } },
      },
    }
  }

  return spec
}
