import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs'
import { join } from 'path'
import { exec } from 'child_process'
import { promisify } from 'util'
import { 
  createExecutionJournal, 
  recordAction, 
  markSuccess, 
  markFailure, 
  closeJournal 
} from './execution-journal'

const execAsync = promisify(exec)

export interface ExecutionResult {
  success: boolean
  message: string
  filesCreated?: string[]
  filesModified?: string[]
  commandsRun?: string[]
  errors?: string[]
  output?: string
}

/**
 * LAYER 3: Execution Engine
 * This is what transforms AI from "helper" to "operator"
 * 
 * Capabilities:
 * 1. Write Prisma schemas
 * 2. Create API routes
 * 3. Run migrations
 * 4. Generate code files
 * 5. Execute safe commands
 */

/**
 * Execute a single action from the AI plan
 */
export async function executeAction(
  action: string,
  description: string,
  code: string | undefined,
  projectId: string,
  workspacePath: string
): Promise<ExecutionResult> {
  console.log(`🔧 Executing: ${action}`)
  console.log(`📝 Description: ${description}`)

  try {
    switch (action) {
      case 'CREATE_PRISMA_MODEL':
        return await createPrismaModel(code!, projectId, workspacePath)
      
      case 'CREATE_API_ROUTE':
        return await createAPIRoute(code!, description, projectId, workspacePath)
      
      case 'RUN_MIGRATION':
        return await runMigration(projectId, workspacePath)
      
      case 'MODIFY_ENV':
        return await modifyEnvFile(description, code!, projectId, workspacePath)
      
      case 'GENERATE_AUTH':
        return await generateAuthSetup(projectId, workspacePath)
      
      case 'CREATE_STORAGE_BUCKET':
        return await createStorageBucket(description, projectId)
      
      case 'CREATE_DATABASE_TABLE':
        return await createDatabaseTable(code || description, projectId)
      
      case 'INSERT_MOCK_DATA':
        return await insertMockData(code || description, projectId)

      // CREATE_API_DEFINITION is gone (2026-07-21). Under PostgREST the API IS
      // the schema: a table is reachable because it exists and the role holds a
      // grant, resolved from the PostgreSQL catalog per request. An ApiDefinition
      // row decided nothing and could only disagree with the catalog, so the
      // action now falls through to "unknown" rather than writing one.
      default:
        return {
          success: false,
          message: `Unknown action: ${action}`,
          errors: [`Action type "${action}" is not supported`],
        }
    }
  } catch (error: any) {
    console.error(`❌ Execution failed:`, error)
    return {
      success: false,
      message: `Execution failed: ${error.message}`,
      errors: [error.message],
    }
  }
}

/**
 * Create or update Prisma model in schema
 */
async function createPrismaModel(
  modelCode: string,
  projectId: string,
  workspacePath: string
): Promise<ExecutionResult> {
  const schemaPath = join(workspacePath, 'prisma', 'schema.prisma')
  const envPath = join(workspacePath, '.env')
  
  try {
    // Ensure prisma directory exists
    const prismaDir = join(workspacePath, 'prisma')
    if (!existsSync(prismaDir)) {
      mkdirSync(prismaDir, { recursive: true })
    }

    // Read existing schema or create default
    let existingSchema = ''
    if (existsSync(schemaPath)) {
      existingSchema = readFileSync(schemaPath, 'utf-8')
    } else {
      existingSchema = `// Prisma Schema for Project: ${projectId}
// Generated by Backenly AI

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`
    }

    // Extract model name from the new model code
    const modelNameMatch = modelCode.match(/model\s+(\w+)\s*{/)
    if (!modelNameMatch) {
      throw new Error('Could not extract model name from code')
    }
    const newModelName = modelNameMatch[1]
    
    // Check if model already exists in schema
    const modelRegex = new RegExp(`model\\s+${newModelName}\\s*{`, 'i')
    if (modelRegex.test(existingSchema)) {
      console.log(`⚠️ Model "${newModelName}" already exists in schema - skipping (idempotent)`)
      return {
        success: true,
        message: `Model "${newModelName}" already exists in schema (no changes needed)`,
        filesModified: [],
      }
    }
    
    // Append new model
    const updatedSchema = existingSchema + '\n' + modelCode + '\n'
    
    // Write to file
    writeFileSync(schemaPath, updatedSchema, 'utf-8')
    console.log(`✅ Prisma model written to: ${schemaPath}`)

    // 🔧 Create .env file with workspace-specific DATABASE_URL
    if (!existsSync(envPath)) {
      // Get the main DATABASE_URL and modify it to use workspace schema
      const mainDbUrl = process.env.DATABASE_URL || ''
      const workspaceSchema = `workspace_${projectId}`
      
      // Add schema parameter to the connection string
      const workspaceDbUrl = mainDbUrl.includes('?')
        ? `${mainDbUrl}&schema=${workspaceSchema}`
        : `${mainDbUrl}?schema=${workspaceSchema}`
      
      const envContent = `# Auto-generated by Backenly AI\nDATABASE_URL="${workspaceDbUrl}"\n`
      writeFileSync(envPath, envContent, 'utf-8')
      console.log(`✅ Created .env file with workspace DATABASE_URL`)
    }

    return {
      success: true,
      message: `Prisma model created successfully`,
      filesCreated: existingSchema === '' ? [schemaPath, envPath] : undefined,
      filesModified: existingSchema !== '' ? [schemaPath] : undefined,
    }
  } catch (error: any) {
    return {
      success: false,
      message: `Failed to create Prisma model: ${error.message}`,
      errors: [error.message],
    }
  }
}

/**
 * Create API route file
 */
async function createAPIRoute(
  routeCode: string,
  description: string,
  projectId: string,
  workspacePath: string
): Promise<ExecutionResult> {
  try {
    // Extract route name from description or code
    const routeName = extractRouteName(description)
    const apiPath = join(workspacePath, 'api', routeName)
    const routeFile = join(apiPath, 'route.ts')

    // Create directory
    if (!existsSync(apiPath)) {
      mkdirSync(apiPath, { recursive: true })
    }

    // Write route code
    writeFileSync(routeFile, routeCode, 'utf-8')
    console.log(`✅ API route created: ${routeFile}`)

    return {
      success: true,
      message: `API route created: /api/${routeName}`,
      filesCreated: [routeFile],
    }
  } catch (error: any) {
    return {
      success: false,
      message: `Failed to create API route: ${error.message}`,
      errors: [error.message],
    }
  }
}

/**
 * Run Prisma migration
 */
async function runMigration(
  projectId: string,
  workspacePath: string
): Promise<ExecutionResult> {
  try {
    console.log(`🔄 Running Prisma migration for project: ${projectId}`)

    // 🔧 FIX: Skip generate to avoid Windows EPERM file locking
    // The main app already has Prisma client generated
    // We just need to sync the schema to the database
    console.log(`🚀 Running prisma db push (skipping generate)...`)
    
    const { stdout: pushOut, stderr: pushErr } = await execAsync(
      'npx prisma db push --skip-generate --accept-data-loss',
      { cwd: workspacePath, timeout: 60000 }
    )

    console.log(`✅ Prisma push output:`, pushOut)
    if (pushErr) console.log(`⚠️ Prisma push stderr:`, pushErr)

    return {
      success: true,
      message: 'Database migration completed successfully',
      commandsRun: ['npx prisma db push --skip-generate'],
      output: pushOut,
    }
  } catch (error: any) {
    console.error(`❌ Migration failed:`, error)
    return {
      success: false,
      message: `Migration failed: ${error.message}`,
      errors: [error.message, error.stderr || error.stdout].filter(Boolean),
      output: error.stdout || error.stderr,
    }
  }
}

/**
 * Modify environment variables
 */
async function modifyEnvFile(
  description: string,
  envVars: string,
  projectId: string,
  workspacePath: string
): Promise<ExecutionResult> {
  try {
    const envPath = join(workspacePath, '.env')
    
    // Read existing or create new
    let existingEnv = existsSync(envPath) ? readFileSync(envPath, 'utf-8') : ''
    
    // Append new variables
    const updatedEnv = existingEnv + '\n' + envVars + '\n'
    
    writeFileSync(envPath, updatedEnv, 'utf-8')
    console.log(`✅ Environment variables updated`)

    return {
      success: true,
      message: 'Environment variables updated',
      filesModified: [envPath],
    }
  } catch (error: any) {
    return {
      success: false,
      message: `Failed to update .env: ${error.message}`,
      errors: [error.message],
    }
  }
}

/**
 * Generate authentication setup
 */
async function generateAuthSetup(
  projectId: string,
  workspacePath: string
): Promise<ExecutionResult> {
  try {
    const filesCreated: string[] = []

    // Create auth middleware
    const middlewarePath = join(workspacePath, 'api', 'middleware', 'auth.ts')
    const middlewareDir = join(workspacePath, 'api', 'middleware')
    
    if (!existsSync(middlewareDir)) {
      mkdirSync(middlewareDir, { recursive: true })
    }

    const authMiddleware = `import { NextRequest, NextResponse } from 'next/server'
import jwt from 'jsonwebtoken'

export async function requireAuth(request: NextRequest) {
  const token = request.headers.get('Authorization')?.replace('Bearer ', '')
  
  if (!token) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET!)
    return decoded
  } catch (error) {
    return NextResponse.json({ error: 'Invalid token' }, { status: 401 })
  }
}
`

    writeFileSync(middlewarePath, authMiddleware, 'utf-8')
    filesCreated.push(middlewarePath)

    // Create login route
    const loginPath = join(workspacePath, 'api', 'auth', 'login', 'route.ts')
    const loginDir = join(workspacePath, 'api', 'auth', 'login')
    
    if (!existsSync(loginDir)) {
      mkdirSync(loginDir, { recursive: true })
    }

    const loginRoute = `import { NextRequest, NextResponse } from 'next/server'
import jwt from 'jsonwebtoken'
import bcrypt from 'bcryptjs'

export async function POST(request: NextRequest) {
  const { email, password } = await request.json()
  
  // TODO: Query user from database
  // const user = await prisma.user.findUnique({ where: { email } })
  
  // TODO: Verify password
  // const valid = await bcrypt.compare(password, user.password)
  
  // Generate JWT
  const token = jwt.sign(
    { userId: 'user-id', email },
    process.env.JWT_SECRET!,
    { expiresIn: '7d' }
  )
  
  return NextResponse.json({ token })
}
`

    writeFileSync(loginPath, loginRoute, 'utf-8')
    filesCreated.push(loginPath)

    console.log(`✅ Auth setup generated`)

    return {
      success: true,
      message: 'Authentication setup created',
      filesCreated,
    }
  } catch (error: any) {
    return {
      success: false,
      message: `Failed to generate auth: ${error.message}`,
      errors: [error.message],
    }
  }
}

/**
 * Create storage bucket (via database)
 */
async function createStorageBucket(
  description: string,
  projectId: string
): Promise<ExecutionResult> {
  try {
    const { prisma } = await import('@/lib/db')
    
    const bucketName = extractBucketName(description)
    
    const bucket = await prisma.storageBucket.create({
      data: {
        name: bucketName,
        projectId,
        isPublic: description.toLowerCase().includes('public'),
        maxFileSizeBytes: BigInt(10 * 1024 * 1024), // 10MB default
      },
    })

    console.log(`✅ Storage bucket created: ${bucketName}`)

    return {
      success: true,
      message: `Storage bucket "${bucketName}" created`,
    }
  } catch (error: any) {
    return {
      success: false,
      message: `Failed to create bucket: ${error.message}`,
      errors: [error.message],
    }
  }
}

/**
 * Create database table directly in workspace database
 */
async function createDatabaseTable(
  tableInfo: string | any,
  projectId: string
): Promise<ExecutionResult> {
  try {
    const { getWorkspaceDatabaseNames } = await import('@/lib/services/databaseProvisioning')
    const { executeInWorkspaceSchema } = await import('@/lib/services/workspaceDatabase')
    const { prisma } = await import('@/lib/db')
    
    // Parse table info - could be JSON object, JSON string, or natural language
    let tableName: string
    let columns: Array<{ name: string; type: string; nullable?: boolean; primary?: boolean }>
    
    // If tableInfo is already an object, use it directly
    if (typeof tableInfo === 'object' && tableInfo !== null) {
      tableName = tableInfo.tableName || tableInfo.name
      columns = tableInfo.columns || tableInfo.schema
      console.log(`📝 Received table object:`, { tableName, columnCount: columns?.length })
    } else {
      // It's a string - try parsing as JSON first
      try {
        const parsed = JSON.parse(tableInfo)
        tableName = parsed.tableName || parsed.name
        columns = parsed.columns || parsed.schema
      } catch {
        // Parse from natural language (e.g., "create a review table with id, title, content, rating columns")
        const match = tableInfo.match(/(?:create|table)\s+(?:a\s+|an\s+)?([\w_]+)/i)
        if (!match) {
          throw new Error('Could not extract table name from request')
        }
        tableName = match[1].toLowerCase()
        
        // Generate basic schema
        columns = [
          { name: 'id', type: 'SERIAL', primary: true },
          { name: 'created_at', type: 'TIMESTAMP', nullable: false },
          { name: 'updated_at', type: 'TIMESTAMP', nullable: false },
        ]
        
        // Try to extract column names from description
        const columnMatches = tableInfo.match(/(?:with|columns?|fields?)\s+([^.]+)/i)
        if (columnMatches) {
          const columnNames = columnMatches[1]
            .split(/[,;]|\s+and\s+/i)
            .map(c => c.trim().replace(/\s+columns?$/i, ''))
            .filter(Boolean)
          
          columnNames.forEach(colName => {
            if (!['id', 'created_at', 'updated_at'].includes(colName.toLowerCase())) {
              // Guess column type from name
              let type = 'TEXT'
              if (colName.toLowerCase().includes('email')) type = 'TEXT'
              else if (colName.toLowerCase().includes('password')) type = 'TEXT'
              else if (colName.toLowerCase().includes('rating') || colName.toLowerCase().includes('count')) type = 'INTEGER'
              else if (colName.toLowerCase().includes('price') || colName.toLowerCase().includes('amount')) type = 'DECIMAL(10,2)'
              else if (colName.toLowerCase().includes('date')) type = 'TIMESTAMP'
              else if (colName.toLowerCase().includes('is_') || colName.toLowerCase().includes('active')) type = 'BOOLEAN'
              
              columns.push({ name: colName.toLowerCase(), type, nullable: true })
            }
          })
        }
      }
    }
    
    console.log(`🗄️ Creating table "${tableName}" with ${columns.length} columns`)
    
    // Get workspace database info
    const dbNames = getWorkspaceDatabaseNames(projectId)
    const targetSchema = dbNames.postgresSchema
    
    // Generate CREATE TABLE SQL
    const columnDefs = columns.map(col => {
      const parts = [
        col.name,
        col.type,
        col.primary ? 'PRIMARY KEY' : '',
        col.nullable === false ? 'NOT NULL' : '',
        col.name === 'created_at' ? 'DEFAULT CURRENT_TIMESTAMP' : '',
        col.name === 'updated_at' ? 'DEFAULT CURRENT_TIMESTAMP' : '',
      ].filter(Boolean)
      return parts.join(' ')
    }).join(',\n  ')
    
    const createTableSQL = `
CREATE TABLE IF NOT EXISTS "${targetSchema}"."${tableName}" (
  ${columnDefs}
);
`
    
    console.log(`📝 SQL:\n${createTableSQL}`)
    
    // Execute CREATE TABLE
    await executeInWorkspaceSchema(projectId, createTableSQL)
    
    // Save to platform metadata (check if exists first)
    const existingTable = await prisma.table.findFirst({
      where: {
        projectId,
        name: tableName,
        schema: targetSchema,
      },
    })
    
    if (!existingTable) {
      await prisma.table.create({
        data: {
          projectId,
          name: tableName,
          schema: targetSchema,
          description: `Table created by AI Assistant`,
        },
      })
    } else {
      console.log(`ℹ️ Table metadata already exists, skipping insert`)
    }
    
    console.log(`✅ Table "${tableName}" created successfully`)
    
    return {
      success: true,
      message: `Table "${tableName}" created in database with ${columns.length} columns`,
    }
  } catch (error: any) {
    console.error(`❌ Failed to create table:`, error)
    return {
      success: false,
      message: `Failed to create table: ${error.message}`,
      errors: [error.message],
    }
  }
}

/**
 * Insert mock data into an existing table
 */
async function insertMockData(
  dataInfo: string | any,
  projectId: string
): Promise<ExecutionResult> {
  try {
    const { getWorkspaceDatabaseNames } = await import('@/lib/services/databaseProvisioning')
    const { executeInWorkspaceSchema } = await import('@/lib/services/workspaceDatabase')
    
    let tableName: string
    let rows: Array<Record<string, any>>
    
    // Parse data info - could be object or JSON string
    if (typeof dataInfo === 'object' && dataInfo !== null) {
      // If it's an array, it's the rows directly
      if (Array.isArray(dataInfo)) {
        rows = dataInfo
        // Extract table name from first row or fail
        throw new Error('Table name not provided. Please specify tableName in the request.')
      } else {
        tableName = dataInfo.tableName || dataInfo.table
        rows = dataInfo.rows || dataInfo.data || []
        
        // If rows is still an object (not array), wrap it
        if (!Array.isArray(rows) && typeof rows === 'object') {
          rows = [rows]
        }
      }
    } else if (typeof dataInfo === 'string') {
      // Check if it's a description (not JSON)
      if (!dataInfo.trim().startsWith('{') && !dataInfo.trim().startsWith('[')) {
        // It's a description like "Insert sample data into the Addresses table"
        // Extract table name
        const tableMatch = dataInfo.match(/(?:into|to|in)\s+(?:the\s+)?([\w_]+)\s+table/i)
        if (tableMatch) {
          tableName = tableMatch[1]
          // Return error asking user to provide data
          return {
            success: false,
            message: `Please provide the actual data to insert. Example: "insert {userId: 1, street: '123 Main St', city: 'NY', state: 'CA', zipCode: '12345'} into ${tableName}"`,
            errors: ['No data provided in the request'],
          }
        } else {
          throw new Error('Could not extract table name from description. Please specify: "insert data into TABLE_NAME"')
        }
      }
      
      // Try parsing as JSON
      const parsed = JSON.parse(dataInfo)
      if (Array.isArray(parsed)) {
        rows = parsed
        throw new Error('Table name not provided. Please specify tableName in the request.')
      } else {
        tableName = parsed.tableName || parsed.table
        rows = parsed.rows || parsed.data
      }
    } else {
      throw new Error('Invalid data format provided')
    }
    
    if (!tableName) {
      throw new Error('Table name is required')
    }
    
    if (!rows || !Array.isArray(rows) || rows.length === 0) {
      throw new Error('No data rows provided')
    }
    
    console.log(`📝 Inserting ${rows.length} rows into table "${tableName}"`)
    
    // Get workspace database info
    const dbNames = getWorkspaceDatabaseNames(projectId)
    const targetSchema = dbNames.postgresSchema
    
    // Query actual table structure from PostgreSQL
    const { prisma } = await import('@/lib/db')
    
    console.log(`🔍 Querying actual columns for table "${tableName}" in schema "${targetSchema}"`)
    
    // First, find the actual table name (case-insensitive match)
    const tableExistsQuery = `
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = '${targetSchema}' 
      AND LOWER(table_name) = LOWER('${tableName}');
    `
    
    const tableResults: Array<{ table_name: string }> = await prisma.$queryRawUnsafe(tableExistsQuery)
    
    if (tableResults.length === 0) {
      throw new Error(`Table "${tableName}" not found in schema "${targetSchema}". Please verify the table exists.`)
    }
    
    // Use the actual table name from database (correct casing)
    const actualTableName = tableResults[0].table_name
    if (actualTableName !== tableName) {
      console.log(`📝 Corrected table name: "${tableName}" → "${actualTableName}"`)
      tableName = actualTableName
    }
    
    // Now query columns for the correct table name
    const columnsQuery = `
      SELECT column_name, data_type 
      FROM information_schema.columns 
      WHERE table_schema = '${targetSchema}' 
      AND table_name = '${tableName}'
      ORDER BY ordinal_position;
    `
    
    const actualColumns: Array<{ column_name: string; data_type: string }> = await prisma.$queryRawUnsafe(columnsQuery)
    
    const actualColumnNames = actualColumns.map(c => c.column_name)
    console.log(`✅ Found ${actualColumns.length} columns:`, actualColumnNames.join(', '))
    
    // Map user-provided data to actual column names (case-insensitive match)
    const mappedRows = rows.map(row => {
      const mappedRow: Record<string, any> = {}
      
      // Match each provided column to actual column (case-insensitive + fuzzy)
      Object.entries(row).forEach(([key, value]) => {
        // Try exact match (case-insensitive)
        let actualCol = actualColumnNames.find(c => c.toLowerCase() === key.toLowerCase())
        
        // If no match, try fuzzy matching for common variations
        if (!actualCol) {
          const keyLower = key.toLowerCase()
          // zipCode → postalCode
          if (keyLower === 'zipcode' || keyLower === 'zip') {
            actualCol = actualColumnNames.find(c => c.toLowerCase() === 'postalcode')
          }
          // postalCode → zipCode
          else if (keyLower === 'postalcode') {
            actualCol = actualColumnNames.find(c => c.toLowerCase() === 'zipcode')
          }
          // user_id → userId
          else if (keyLower === 'user_id') {
            actualCol = actualColumnNames.find(c => c.toLowerCase() === 'userid')
          }
          // userId → user_id
          else if (keyLower === 'userid') {
            actualCol = actualColumnNames.find(c => c.toLowerCase() === 'user_id')
          }
        }
        
        if (actualCol) {
          mappedRow[actualCol] = value
          if (key !== actualCol) {
            console.log(`📝 Mapped "${key}" → "${actualCol}"`)
          }
        } else {
          console.warn(`⚠️ Column "${key}" not found in table, skipping`)
        }
      })
      
      // Add timestamps if not provided
      if (!mappedRow.createdAt && !mappedRow.created_at && actualColumnNames.some(c => c.toLowerCase() === 'createdat')) {
        const col = actualColumnNames.find(c => c.toLowerCase() === 'createdat')!
        mappedRow[col] = new Date().toISOString()
      }
      if (!mappedRow.updatedAt && !mappedRow.updated_at && actualColumnNames.some(c => c.toLowerCase() === 'updatedat')) {
        const col = actualColumnNames.find(c => c.toLowerCase() === 'updatedat')!
        mappedRow[col] = new Date().toISOString()
      }
      
      return mappedRow
    })
    
    // Generate INSERT statements
    const insertPromises = mappedRows.map(async (row) => {
      const columns = Object.keys(row)
      const values = Object.values(row)
      
      // Format values for SQL
      const formattedValues = values.map(v => {
        if (v === null) return 'NULL'
        if (typeof v === 'string') return `'${v.replace(/'/g, "''")}'`
        if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE'
        if (v instanceof Date) return `'${v.toISOString()}'`
        return v
      }).join(', ')
      
      const insertSQL = `
INSERT INTO "${targetSchema}"."${tableName}" (${columns.map(c => `"${c}"`).join(', ')})
VALUES (${formattedValues});
`
      
      console.log(`📝 SQL: ${insertSQL}`)
      return executeInWorkspaceSchema(projectId, insertSQL)
    })
    
    await Promise.all(insertPromises)
    
    console.log(`✅ Inserted ${rows.length} rows into "${tableName}"`)
    
    return {
      success: true,
      message: `Successfully inserted ${rows.length} rows into table "${tableName}"`,
    }
  } catch (error: any) {
    console.error(`❌ Failed to insert mock data:`, error)
    return {
      success: false,
      message: `Failed to insert data: ${error.message}`,
      errors: [error.message],
    }
  }
}

/**
 * Derive a user-facing retry instruction from a failed action type.
 * Returns a short imperative sentence the user can say to retry just that step.
 */
function deriveRetryHint(action: string, description: string): string {
  const hints: Record<string, string> = {
    GENERATE_API:     'Say "generate API for [table name]" to retry the API generation.',
    CREATE_TABLE:     'Say "create [table name] table" to retry creating the table.',
    ENABLE_AUTH:      'Say "enable auth" to retry enabling authentication.',
    CREATE_BUCKET:    'Say "create storage bucket" to retry the storage setup.',
    CREATE_TRIGGER:   'Say "create trigger" to retry the trigger.',
    CREATE_CRON_JOB:  'Say "create cron job" to retry the scheduled job.',
    ADD_COLUMN:       'Say "add [column name] column to [table]" to retry adding the column.',
    CREATE_INDEX:     'Say "add index to [table]" to retry the index creation.',
    SET_PERMISSION:   'Say "set permission on [table]" to retry the permission rule.',
    CREATE_AI_FUNCTION: 'Say "create AI function" to retry the function.',
  }
  // Fall back to description-derived hint
  return hints[action] ?? `Retry by describing what failed: "${description.slice(0, 80)}".`
}

/**
 * Execute entire plan (multiple actions)
 * NOW WITH JOURNALING for crash recovery
 */
export async function executePlan(
  plan: Array<{ action: string; description: string; code?: string }>,
  projectId: string,
  userId?: string
): Promise<ExecutionResult & { journalId?: string }> {
  const workspacePath = join(process.cwd(), 'workspace', projectId)
  const results: ExecutionResult[] = []
  const allFilesCreated: string[] = []
  const allFilesModified: string[] = []
  const allCommandsRun: string[] = []
  const allErrors: string[] = []
  let allStdout = ''

  console.log(`🚀 Executing plan with ${plan.length} steps...`)

  // 📋 STEP 1: Create execution journal BEFORE execution
  const journal = createExecutionJournal(
    projectId,
    userId || 'system',
    `plan-${Date.now()}`,
    `Execute ${plan.length} steps`,
    plan.length
  )
  
  console.log(`📔 Created journal: ${journal.id}`)

  try {
    for (let i = 0; i < plan.length; i++) {
      const step = plan[i]
      console.log(`📋 Step ${i + 1}/${plan.length}: ${step.action}`)

      // 📖 Record action BEFORE executing (for rollback)
      const entry = recordAction(
        journal.id,
        i + 1,
        step.action,
        step.description,
        workspacePath
      )

      // ⚡ EXECUTE (Real code)
      const result = await executeAction(
        step.action,
        step.description,
        step.code,
        projectId,
        workspacePath
      )

      results.push(result)

      if (result.success) {
        // ✅ Mark as successful in journal
        markSuccess(
          journal.id,
          entry.id,
          result.output || result.message,
          result.filesCreated?.map(f => ({ type: 'file_created' as const, target: f })) || []
        )
        
        if (result.filesCreated) allFilesCreated.push(...result.filesCreated)
        if (result.filesModified) allFilesModified.push(...result.filesModified)
        if (result.commandsRun) allCommandsRun.push(...result.commandsRun)
        if (result.output) allStdout += result.output + '\n'
      } else {
        // ❌ Mark as failed in journal
        markFailure(
          journal.id,
          entry.id,
          result.errors?.[0] || result.message
        )

        if (result.errors) allErrors.push(...result.errors)
        console.error(`❌ Step ${i + 1} failed, stopping execution`)
        closeJournal(journal.id, 'failed')

        // Build a precise partial-failure message so the user knows exactly what was
        // completed and what still needs to happen, and can issue a targeted retry.
        const completedSteps = plan.slice(0, i).map((s, idx) => `✓ Step ${idx + 1}: ${s.description}`)
        const failedStep = `✗ Step ${i + 1}: ${step.description} — ${result.errors?.[0] || result.message}`
        const remainingSteps = plan.slice(i + 1).map((s, idx) => `⏸ Step ${i + 2 + idx}: ${s.description}`)

        const partialLines: string[] = ['**Partial execution — stopped after error:**', '']
        if (completedSteps.length > 0) partialLines.push(...completedSteps, '')
        partialLines.push(failedStep)
        if (remainingSteps.length > 0) partialLines.push('', ...remainingSteps)

        // Derive a recovery hint from the failed step's action so the user can retry it
        const retryHint = deriveRetryHint(step.action, step.description)
        if (retryHint) partialLines.push('', `**To continue:** ${retryHint}`)

        return {
          success: false,
          message: partialLines.join('\n'),
          filesCreated: allFilesCreated.length > 0 ? allFilesCreated : undefined,
          filesModified: allFilesModified.length > 0 ? allFilesModified : undefined,
          commandsRun: allCommandsRun.length > 0 ? allCommandsRun : undefined,
          errors: allErrors.length > 0 ? allErrors : undefined,
          output: allStdout || undefined,
          journalId: journal.id,
        }
      }
    }

    const allSuccess = results.every((r) => r.success)
    const successCount = results.filter((r) => r.success).length

    // Close journal
    closeJournal(journal.id, allSuccess ? 'completed' : 'failed')

    return {
      success: allSuccess,
      message: allSuccess
        ? `All ${plan.length} steps completed successfully`
        : `Completed ${successCount}/${plan.length} steps before error`,
      filesCreated: allFilesCreated.length > 0 ? allFilesCreated : undefined,
      filesModified: allFilesModified.length > 0 ? allFilesModified : undefined,
      commandsRun: allCommandsRun.length > 0 ? allCommandsRun : undefined,
      errors: allErrors.length > 0 ? allErrors : undefined,
      output: allStdout || undefined,
      journalId: journal.id,
    }
  } catch (error: any) {
    console.error(`🔥 EXECUTION ENGINE CRASH:`, error)
    closeJournal(journal.id, 'failed')
    
    return {
      success: false,
      message: `Execution engine crashed: ${error.message}`,
      errors: [error.message],
      journalId: journal.id,
    }
  }
}

/**
 * Helper: Extract route name from description
 */
function extractRouteName(description: string): string {
  const match = description.match(/\b(todos|users|posts|products|items|auth|login|signup)\b/i)
  return match ? match[1].toLowerCase() : 'endpoint'
}

/**
 * Helper: Extract bucket name from description
 */
function extractBucketName(description: string): string {
  const match = description.match(/\b(images|files|videos|documents|avatars|uploads)\b/i)
  return match ? match[1].toLowerCase() : 'files'
}
