/**
 * TYPE GENERATOR
 * ==============
 * Converts a WorkspaceSchema (from schema-reader) into a TypeScript
 * declaration string (.d.ts) containing:
 *
 *   - <TableName>Row      — shape returned by SELECT
 *   - <TableName>Insert   — shape accepted by INSERT (auto-cols omitted)
 *   - <TableName>Update   — Partial<Insert> for PATCH/PUT
 *   - Database            — master type map (table → { Row, Insert, Update })
 *   - TableName           — union of all table name strings
 */

import type { ColumnInfo, WorkspaceSchema, TableSchema } from './schema-reader'

// ── PG → TS type mapping ────────────────────────────────────────────────────

const PG_TO_TS: Record<string, string> = {
  // Text
  text: 'string',
  varchar: 'string',
  'character varying': 'string',
  character: 'string',
  char: 'string',
  name: 'string',
  citext: 'string',
  // Numbers
  integer: 'number',
  int: 'number',
  int2: 'number',
  int4: 'number',
  int8: 'number',
  smallint: 'number',
  bigint: 'number',
  bigserial: 'number',
  serial: 'number',
  smallserial: 'number',
  numeric: 'number',
  decimal: 'number',
  real: 'number',
  float4: 'number',
  float8: 'number',
  'double precision': 'number',
  money: 'number',
  // Boolean
  boolean: 'boolean',
  bool: 'boolean',
  // UUID
  uuid: 'string',
  // Date / time
  date: 'string',
  time: 'string',
  'time without time zone': 'string',
  'time with time zone': 'string',
  timestamp: 'string',
  'timestamp without time zone': 'string',
  'timestamp with time zone': 'string',
  timestamptz: 'string',
  interval: 'string',
  // JSON
  json: 'Record<string, unknown>',
  jsonb: 'Record<string, unknown>',
  // Binary
  bytea: 'string',
  // Misc
  oid: 'number',
  inet: 'string',
  cidr: 'string',
  macaddr: 'string',
  bit: 'string',
  varbit: 'string',
  xml: 'string',
  // ARRAY (udt_name starts with _)
  ARRAY: 'unknown[]',
}

/** Map a single PostgreSQL column to its TypeScript type string. */
export function pgTypeToTs(col: ColumnInfo): string {
  // Arrays: udt_name starts with "_" e.g. "_text" → string[]
  if (col.dataType === 'ARRAY') {
    const elementUdt = col.udtName.startsWith('_') ? col.udtName.slice(1) : col.udtName
    const elementTs = PG_TO_TS[elementUdt] ?? 'unknown'
    return `${elementTs}[]`
  }

  const ts =
    PG_TO_TS[col.dataType] ??
    PG_TO_TS[col.udtName] ??
    'unknown'

  return ts
}

// ── Auto-generated column detection ─────────────────────────────────────────

const AUTO_GENERATED_DEFAULTS = [
  'gen_random_uuid()',
  'uuid_generate_v4()',
  "nextval(",
  'now()',
  'current_timestamp',
  'CURRENT_TIMESTAMP',
]

const AUTO_TIMESTAMP_NAMES = new Set(['created_at', 'createdat', 'updated_at', 'updatedat'])

function isAutoGeneratedColumn(col: ColumnInfo): boolean {
  if (col.isPrimaryKey) return true
  if (
    col.columnDefault &&
    AUTO_GENERATED_DEFAULTS.some(d => col.columnDefault!.toLowerCase().startsWith(d.toLowerCase()))
  ) {
    return true
  }
  if (AUTO_TIMESTAMP_NAMES.has(col.columnName.toLowerCase())) return true
  return false
}

// ── Per-table type block ─────────────────────────────────────────────────────

function toPascalCase(s: string): string {
  return s
    .replace(/_([a-z])/g, (_, c) => c.toUpperCase())
    .replace(/^[a-z]/, c => c.toUpperCase())
}

function generateTableTypes(table: TableSchema): string {
  const pascal = toPascalCase(table.tableName)
  const lines: string[] = []

  // ── Row ──────────────────────────────────────────────────────────────────
  lines.push(`/** Row returned by SELECT on the \`${table.tableName}\` table */`)
  lines.push(`export interface ${pascal}Row {`)
  for (const col of table.columns) {
    const ts = pgTypeToTs(col)
    const nullable = col.isNullable ? ` | null` : ''
    lines.push(`  ${col.columnName}: ${ts}${nullable};`)
  }
  lines.push(`}`)
  lines.push('')

  // ── Insert ───────────────────────────────────────────────────────────────
  const insertCols = table.columns.filter(c => !isAutoGeneratedColumn(c))
  lines.push(`/** Data accepted when inserting into \`${table.tableName}\` */`)
  lines.push(`export interface ${pascal}Insert {`)
  for (const col of insertCols) {
    const ts = pgTypeToTs(col)
    const optional = col.isNullable || col.columnDefault !== null ? '?' : ''
    const nullable = col.isNullable ? ` | null` : ''
    lines.push(`  ${col.columnName}${optional}: ${ts}${nullable};`)
  }
  lines.push(`}`)
  lines.push('')

  // ── Update ───────────────────────────────────────────────────────────────
  lines.push(`/** Data accepted when updating \`${table.tableName}\` */`)
  lines.push(`export type ${pascal}Update = Partial<${pascal}Insert>;`)
  lines.push('')

  return lines.join('\n')
}

// ── Database master map ──────────────────────────────────────────────────────

function generateDatabaseType(tables: TableSchema[]): string {
  const lines: string[] = []
  lines.push('/** Master type map — pass this to createTypedClient<Database>() */')
  lines.push('export interface Database {')
  for (const table of tables) {
    const pascal = toPascalCase(table.tableName)
    lines.push(`  ${table.tableName}: {`)
    lines.push(`    Row: ${pascal}Row;`)
    lines.push(`    Insert: ${pascal}Insert;`)
    lines.push(`    Update: ${pascal}Update;`)
    lines.push(`  };`)
  }
  lines.push('}')
  lines.push('')
  lines.push('/** Union of all table names in this project */')
  lines.push('export type TableName = keyof Database;')
  lines.push('')
  return lines.join('\n')
}

// ── Public entry point ───────────────────────────────────────────────────────

export interface GeneratedTypes {
  /** Full TypeScript declaration source — save as backenly.types.ts */
  source: string
  /** Names of all tables found */
  tableNames: string[]
}

export function generateTypes(schema: WorkspaceSchema): GeneratedTypes {
  if (schema.tables.length === 0) {
    return {
      source: [
        `// No tables found in workspace_${schema.projectId}`,
        `// Create tables via the AI chat to generate types.`,
        `export interface Database {}`,
        `export type TableName = never;`,
      ].join('\n'),
      tableNames: [],
    }
  }

  const header = [
    `/**`,
    ` * Backenly — auto-generated types for project ${schema.projectId}`,
    ` * Generated: ${schema.generatedAt}`,
    ` *`,
    ` * DO NOT EDIT — regenerate via:`,
    ` *   GET /api/typegen?projectId=${schema.projectId}&format=dts`,
    ` */`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/ban-ts-comment`,
    `// @ts-nocheck — this file is fully auto-generated`,
    ``,
  ].join('\n')

  const tableBlocks = schema.tables.map(generateTableTypes).join('\n')
  const databaseType = generateDatabaseType(schema.tables)

  return {
    source: header + tableBlocks + databaseType,
    tableNames: schema.tables.map(t => t.tableName),
  }
}
