/**
 * The SQL each replay carries, built from hashed evidence and the current schema.
 *
 *   A  the legacy chain, read from tools/migration-lineage/evidence and checked
 *      byte for byte against SHA256SUMS before anything is sent
 *   P  the current schema.prisma projection, generated by the pinned Prisma CLI
 *      without a database
 */

import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { ReplayInput } from './probe/input'

export const EVIDENCE_DIR = 'tools/migration-lineage/evidence'

const sha256 = (buf: Buffer | string) => createHash('sha256').update(buf).digest('hex')

export function assertRepoRoot(root: string): void {
  for (const marker of ['prisma/schema.prisma', 'AGENTS.md', `${EVIDENCE_DIR}/SHA256SUMS`]) {
    if (!existsSync(join(root, marker))) throw new Error(`${root} is not the repository root (no ${marker})`)
  }
}

/** Every evidence file, verified against SHA256SUMS. */
export function verifiedEvidence(root: string): Map<string, string> {
  const listing = readFileSync(join(root, EVIDENCE_DIR, 'SHA256SUMS'), 'utf8').trim().split('\n')
  const sums = new Map<string, string>()
  for (const line of listing) {
    const m = line.match(/^([0-9a-f]{64}) {2}(.+)$/)
    if (!m) throw new Error(`malformed SHA256SUMS line: ${line}`)
    const actual = sha256(readFileSync(join(root, EVIDENCE_DIR, m[2])))
    if (actual !== m[1]) throw new Error(`evidence file ${m[2]} does not match SHA256SUMS`)
    sums.set(m[2], m[1])
  }
  return sums
}

export function buildChainInput(root: string): ReplayInput {
  const sums = verifiedEvidence(root)
  const dir = join(root, EVIDENCE_DIR, 'legacy-prisma-chain')
  // prisma migrate applies migration directories in lexicographic name order,
  // which is why the undated add_auth_security runs last.
  const order = readdirSync(dir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort()
  if (order.length !== 18) throw new Error(`expected 18 legacy migrations, found ${order.length}`)

  const files = order.map(name => {
    const rel = `legacy-prisma-chain/${name}/migration.sql`
    const bytes = readFileSync(join(root, EVIDENCE_DIR, rel))
    if (sums.get(rel) !== sha256(bytes)) throw new Error(`${rel} is not the hashed evidence`)
    const sql = bytes.toString('utf8')
    if (sha256(sql) !== sha256(bytes)) throw new Error(`${rel} does not round-trip through UTF-8`)
    return { name, sql }
  })

  return {
    purpose: 'chain',
    source: {
      kind: 'legacy-prisma-chain',
      evidence: `${EVIDENCE_DIR}/legacy-prisma-chain`,
      order: 'lexicographic directory name, as prisma migrate applies them',
    },
    files,
  }
}

export function buildPushInput(root: string): ReplayInput {
  const schemaPath = join(root, 'prisma', 'schema.prisma')
  const cli = join(root, 'node_modules', 'prisma', 'build', 'index.js')
  const sql = execFileSync(
    process.execPath,
    [cli, 'migrate', 'diff', '--from-empty', '--to-schema-datamodel', schemaPath, '--script'],
    {
      cwd: root,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, PRISMA_HIDE_UPDATE_MESSAGE: '1' },
    },
  )
  if (!/CREATE TABLE/.test(sql)) throw new Error('prisma migrate diff produced no CREATE TABLE')
  const prismaVersion = JSON.parse(readFileSync(join(root, 'node_modules', 'prisma', 'package.json'), 'utf8')).version

  return {
    purpose: 'push',
    source: {
      kind: 'schema-prisma-projection',
      command: 'prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script',
      prismaVersion,
      schemaSha256: sha256(readFileSync(schemaPath)),
    },
    files: [{ name: 'schema.prisma projection', sql }],
  }
}
