/**
 * BRAIN AGENT — the loop
 * ======================
 * The single entry point for the new agentic chat path. Replaces the 25-stage
 * regex pipeline and the legacy `agent-loop-v2`. The shape is the same one
 * Cursor / Replit / Lovable use:
 *
 *   load memory → classify intent → route → (loop tool-use) → verify → finish
 *
 * Routing decisions per intent (made BEFORE the agent loop runs):
 *   CHAT            → call answer_question tool once, return.
 *   UNCLEAR         → call ask_user once, return.
 *   APPLY_PROPOSAL  → call apply_proposal once, return.
 *   CONFIRM         → resume any pending plan (currently surfaced via context;
 *                     the agent prompt is told the prior plan exists).
 *   BUILD / MODIFY / FIX / QUESTION / DESTRUCTIVE → enter the agent loop with
 *                     intent-specific hints in the system prompt.
 *
 * This is what makes "give me competitors" NEVER trigger a build:
 *   1. The LLM classifier returns CHAT with high confidence.
 *   2. We dispatch answer_question directly, bypassing every mutation tool.
 *   3. The agent loop never even sees the mutation tool surface for that turn.
 */

import type { OpenAI } from 'openai'
import { getOpenAIClient, trackCompletionCost } from '../openai-service'
import { getModel } from '../model-router'
import { agentSystemPrompt, clarifyPrompt } from './prompts'
import { collectProof, formatProof } from '../proof-system'
import { loadBrainMemory, formatUnderstanding, formatRecentHistory, saveTurn, type ConversationTurn } from './memory'
import { classify, type BrainIntent, type Classification } from './classifier'
import {
  BRAIN_TOOLS,
  dispatchTool,
  isDestructiveTool,
  isReadOnlyTool,
  humanTitle,
  type ToolDispatchContext,
  type ToolName,
} from './tools'
import { getBlueprintForPrompt, isExplicitSpec } from '../blueprints'
import { looksLikeBuildDescription } from './build-signals'
import { findOriginalBuildPrompt } from './resume-routing'
import {
  savePendingPlan, loadPendingPlan, clearPendingPlan,
  saveResumeQueue, loadResumeQueue, clearResumeQueue,
} from '../blueprints/store'
import type { Blueprint, BlueprintMatch, BlueprintStep } from '../blueprints/types'
import {
  extractRequirements,
  appliedStateFromSteps,
  reconcileLedger,
  renderLedgerReport,
  ledgerHasContent,
  type RequirementsLedger,
} from '../blueprints/ledger'
import { createSeedContext, runSeedStep, type SeedTableResult } from '../blueprints/seed-runner'
import type { FixLoopResult } from '../agentic-fix-loop'
import { recordToolExecutionMemory, type BackendEventStatus } from '@/lib/operational-memory/ledger'
import {
  savePendingDestructive, loadPendingDestructive, clearPendingDestructive,
  isDestructiveConfirmation, isBareAffirmative, describePendingDestructive,
  type PendingDestructive, type PendingDestructiveCall,
} from './pending-destructive'

/**
 * Control-flow tools — neither mutations nor reads of backend state.
 * (Reads are tracked in tools.READ_ONLY_TOOLS; mutations are everything else.)
 */
const CONTROL_TOOLS = new Set<string>([
  'finish', 'propose_plan', 'ask_user', 'answer_question',
  'apply_proposal', 'run_test', 'rollback',
])

/**
 * Tools that read their own result back out of the live catalog before they
 * return, and fail rather than report an unconfirmed change.
 *
 * Membership is a claim about the EXECUTOR, not a convenience: a tool belongs
 * here only if ok:true already means "PostgreSQL was asked what it now contains
 * and the answer matched". `set_rls` and `add_rls` share
 * installCustomPolicySet, which re-reads pg_policies per command and restores
 * the table if a policy it just created is not there.
 *
 * Anything listed here that does NOT do that would suppress the verification
 * pass while proving nothing — strictly worse than not being listed.
 */
const SELF_VERIFYING_TOOLS = new Set<string>(['set_rls', 'add_rls'])

export interface BrainInput {
  projectId: string
  userId: string
  message: string
  sessionToken?: string
  /** Pre-confirmed destructive turn (e.g. the prior user message said "yes drop it"). */
  destructiveConfirmed?: boolean
  /**
   * Per-turn idempotency key generated by the chat client (UUID). Passed all
   * the way down to `saveTurn`/`saveMessages` so the conversation log dedups
   * cleanly across writers (route handler, brain terminal paths, retries).
   */
  requestId?: string | null
  /**
   * The product section the user is looking at while typing (the chat dock is
   * global — §7 page-aware context). E.g. "Database", "Auth & Users",
   * "Monitoring". Advisory only: lets "add an index to this table" or "why is
   * this failing" resolve without re-asking. Never required.
   */
  surface?: string | null
  /**
   * ── The wall-clock deadline this turn must respect (epoch ms) ───────────────
   *
   * Verification used to be the LAST thing the loop did, so it was always the
   * thing a wall-clock cap cut off. Four out of four RLS calls over MCP came back
   * "reached its time budget during final verification" — meaning the operations
   * that most needed proof were exactly the ones that never got any.
   *
   * With a deadline the loop stops taking NEW work while `VERIFY_RESERVE_MS`
   * still remains and spends that reserve on a deterministic verification pass
   * (see `verifyWithinBudget`). Verification is no longer a step the model may or
   * may not reach; it is a budget line item that is spent first from the end.
   *
   * Omit it and the loop behaves exactly as before — the dashboard has no hard
   * cap, only the MCP transport does.
   */
  deadlineAt?: number
  /**
   * ── Token reporting that survives an abort ─────────────────────────────────
   *
   * `BrainResult.tokensUsed` is only readable when the turn RETURNS. Callers
   * that race this function against a wall clock (the MCP transport caps at
   * 90s) never see it on the timeout path, because the race rejects and the
   * result is discarded — so a run that spent 80s of model time was billed
   * nothing at all. That is the most expensive kind of turn to lose.
   *
   * This fires after every completion, as the tokens are actually consumed, so
   * a caller can accumulate them itself and charge what was spent even when the
   * turn never finishes. Reporting incrementally is the only way to make the
   * number survive; returning it cannot, by construction.
   *
   * Must not throw — it is invoked inside the model loop.
   */
  onTokens?: (tokens: number) => void
}

export type BrainEvent =
  | { type: 'phase'; phase: 'understand' | 'classify' | 'route' | 'execute' | 'verify' | 'finish' }
  | { type: 'classification'; intent: BrainIntent; confidence: number; reasoning: string }
  | { type: 'thinking'; text: string }
  | { type: 'tool_start'; tool: string; title: string }
  | { type: 'tool_done'; tool: string; title: string; detail?: string }
  | { type: 'tool_fail'; tool: string; title: string; detail?: string }
  /**
   * A destructive tool was blocked pending explicit user confirmation. Carries
   * everything the chat needs to render a structured danger card: what would
   * be destroyed, how many live rows are at stake (best-effort COUNT), and the
   * exact phrase the Confirm button must send to satisfy the route's
   * DESTRUCTIVE_CONFIRM_RE gate.
   */
  | {
      type: 'danger'
      tool: string
      /** Human target, e.g. "recipes table" / "column notes on recipes". */
      target: string
      /** Live row count of the affected table when cheaply knowable. */
      rowCount: number | null
      /** True when a restore point can bring the structure back. */
      reversible: boolean
      confirmPhrase: string
    }
  | { type: 'final'; summary: string; needsUser: boolean; data?: unknown }
  | { type: 'error'; message: string }

export interface BrainResult {
  success: boolean
  summary: string
  needsUser: boolean
  iterations: number
  toolsRun: string[]
  classification: Classification
  /** Total model tokens consumed this turn — billed as token-backed credits. */
  tokensUsed: number
  /**
   * True when this turn already ran the behavioral fix-loop against the live
   * runtime (the deterministic blueprint executor does). The execute route
   * checks this to avoid running a SECOND, redundant verification pass — which
   * would double the time budget and sign up throwaway end-users twice.
   */
  verifiedInline?: boolean
  /**
   * ── Machine-readable failure classification ─────────────────────────────────
   *
   * The prose in `summary` has always been honest about WHY a turn failed
   * ("I stopped before changing anything because the AI provider rate-limited
   * us"). None of it was machine-readable, so every caller had to regex the
   * summary or give up — and `/api/mcp/chat` gave up, returning a bare
   * `Brain run failed.` with no code, no retryable flag and no indication that
   * the identical request would succeed on a second attempt (defect #14).
   *
   * The rate-limit case is the sharpest version: the brain stopped cleanly and
   * said so, and the only place that reached the agent was the `resultSummary`
   * of a later `check_approval` poll — a field nobody would think to read for it
   * (defect #15).
   *
   * Set only when the turn did not complete cleanly.
   */
  failureCode?: BrainFailureCode
  /**
   * Whether an identical retry has a reasonable chance of succeeding. A rate
   * limit and a model timeout are retryable; running out of steps is not (the
   * caller should say "continue" instead), and neither is a tool that refused on
   * the merits.
   */
  retryable?: boolean
  /**
   * Mutations that ACTUALLY landed this turn, whatever the outcome.
   *
   * Populated even on failure, because "the run stopped" and "nothing changed"
   * are different facts and conflating them is what turns a partial success into
   * a duplicate-creating retry.
   */
  applied?: string[]
  /**
   * The loop stopped early to protect its verification reserve, and DID verify.
   *
   * Distinct from every failure code: nothing went wrong, the run simply ran out
   * of wall clock with work still queued. `summary` carries the verified live
   * state, so the caller can report a truthful partial result instead of a
   * timeout the agent has to guess about.
   */
  budgetStopped?: boolean
  /** True when a verification pass actually ran and its result is in `summary`. */
  verified?: boolean
  /**
   * Mutations that were attempted and REFUSED, with the reason each gave.
   *
   * Present whenever any tool returned ok:false, including on an otherwise
   * successful turn. Without it a multi-item request reported only what worked:
   * six items in, four applied, two silently absent. `applied` says what is now
   * true; this says what still is not, and the caller needs both to know whether
   * the request is actually done.
   */
  refused?: Array<{ title: string; reason: string }>
}

export type BrainFailureCode =
  /** The AI provider returned 429. Retry after a pause. */
  | 'RATE_LIMITED'
  /** The model call timed out. Retryable. */
  | 'MODEL_TIMEOUT'
  /** The model errored for some other reason. Retryable once. */
  | 'MODEL_ERROR'
  /** Hit MAX_ITERATIONS. Not retryable as-is — continue instead. */
  | 'STEP_BUDGET_EXHAUSTED'
  /** The turn ended asking the user something. Not a failure to retry. */
  | 'NEEDS_USER'
  /** A tool refused on the merits. Retrying the same call will refuse again. */
  | 'TOOL_REFUSED'

const MAX_ITERATIONS = 12

/**
 * Wall clock held back from the loop and spent on verification.
 *
 * Sized for one `collectProof` against the live catalog with headroom for a slow
 * connection — a handful of catalog queries, not a model call. Deliberately
 * generous: an unverified "✅" costs more than a step the caller can ask for again.
 */
const VERIFY_RESERVE_MS = 15_000

/**
 * Per-mutation-tool proxy token cost used by the deterministic blueprint
 * executor and `singleToolTurn`.
 *
 * The deterministic paths don't pass the LLM through every step — that's by
 * design (it's what makes a curated build cheap and reproducible). But the
 * tools each do real work: tableLifecycle SQL, REST API generation, RLS
 * policy authoring, OAuth credential exchange, function code emission. The
 * meter must reflect that work, otherwise paid plans look uncapped on the
 * "AI credits" surface and the whole pricing page becomes a lie.
 *
 * Numbers are calibrated against the agent-loop equivalent — the same
 * operation through `runAgentLoop` typically burns this many tokens between
 * the LLM tool-call round-trip + the tool's internal LLM uses. They are
 * proxies, not exact measurements; a future PR can wire per-tool token
 * reporting through the dispatch context and replace the table. Until then
 * this is far better than "0", which is what the deterministic paths returned.
 */
const STEP_TOKEN_COST: Partial<Record<ToolName, number>> = {
  // Schema mutations — real SQL execution + graph + audit writes.
  create_table: 900,
  add_column: 400,
  drop_table: 500,
  create_index: 350,
  // API / Auth / Storage / Realtime / Trigger surfaces — codegen + persistence.
  generate_api: 1200,
  enable_auth: 700,
  add_oauth_provider: 500,
  create_bucket: 400,
  add_rls: 800,
  set_rls: 800,
  create_trigger: 500,
  enable_realtime: 400,
  // Functions / aggregates — internal LLM emission.
  generate_function: 2500,
  generate_aggregate_api: 1400,
  // Higher-level capability turn-ons.
  enable_vector_search: 800,
  create_cron_job: 600,
  set_rate_limit: 300,
  enable_teams: 1200,
  enable_push_notifications: 700,
  send_push: 200,
  rotate_webhook_secret: 300,
  replay_webhook_delivery: 200,
  // Fix / apply paths — re-derive + re-execute, charge near a full build.
  fix_backend: 1800,
  apply_proposal: 1500,
}

/** Default proxy when a tool isn't in the table above but still mutated state. */
const STEP_TOKEN_DEFAULT = 600

function proxyTokensForSteps(tools: readonly string[]): number {
  let sum = 0
  for (const t of tools) {
    sum += STEP_TOKEN_COST[t as ToolName] ?? STEP_TOKEN_DEFAULT
  }
  return sum
}

/** Rotating progress lines shown while the LLM architect designs the backend. */
const ARCHITECT_HEARTBEAT_MESSAGES = [
  'Designing your database schema and table relationships…',
  'Planning REST APIs and row-level security…',
  'Wiring realtime streams, automations, and storage…',
  'Finalising a production-grade backend design…',
] as const

/**
 * Run `work` while emitting a keep-alive progress event every `intervalMs`.
 *
 * WHY THIS EXISTS: the execute route arms a 90s idle watchdog that closes the
 * SSE stream if the brain goes silent (execute/route.ts `IDLE_TIMEOUT_MS`).
 * The LLM architect is a SINGLE 30–180s design call that emits nothing on its
 * own — and `architectBackend` deliberately budgets up to 180s per attempt.
 * Without a heartbeat, any healthy big-spec design that runs past 90s is killed
 * mid-generation and the whole build collapses into the fragile agent loop —
 * the exact failure behind the Founder Outreach "continue" loop. Each emitted
 * event resets the route's idle timer, so a legitimately long design survives.
 */
async function withHeartbeat<T>(
  emit: (e: BrainEvent) => void,
  messages: readonly string[],
  work: () => Promise<T>,
  intervalMs = 15_000,
): Promise<T> {
  emit({ type: 'thinking', text: messages[0] })
  let i = 1
  const timer = setInterval(() => {
    emit({ type: 'thinking', text: messages[i % messages.length] })
    i++
  }, intervalMs)
  try {
    return await work()
  } finally {
    clearInterval(timer)
  }
}

/**
 * Resolve a Blueprint for a prompt, keeping the SSE stream alive during the
 * long architect call. Never throws — a failure resolves to null so the caller
 * falls back to the agent loop exactly as it does today.
 */
async function resolveBlueprintWithHeartbeat(
  message: string,
  projectId: string,
  emit: (e: BrainEvent) => void,
): Promise<Awaited<ReturnType<typeof getBlueprintForPrompt>>> {
  return withHeartbeat(emit, ARCHITECT_HEARTBEAT_MESSAGES, () =>
    getBlueprintForPrompt(message, projectId),
  ).catch((err) => {
    console.error('[Brain] blueprint resolution failed:', err)
    return null
  })
}


/** The main entry point: run one turn of the brain. */
export async function runBrain(
  input: BrainInput,
  emit: (e: BrainEvent) => void,
): Promise<BrainResult> {
  const toolsRun: string[] = []

  // ── DESTRUCTIVE CONFIRM RESUME — structured, before anything else ───────
  // The danger gate persisted exactly which tool call it blocked last turn.
  // If this message confirms it (the card's "Confirm — …" button, a bare
  // "yes"/"confirm", or the user re-stating the same destructive imperative),
  // replay THAT stored call deterministically: no classifier, no pending-plan
  // CONFIRM hijack, no LLM re-derivation. Same structured resume the MCP
  // Review Queue uses on approval. Any other message means the user moved on
  // — clear the state so a stray "yes" later can never fire a forgotten drop.
  const pendingDestructive = await loadPendingDestructive(input.projectId).catch(() => null)
  if (pendingDestructive) {
    if (input.destructiveConfirmed || isDestructiveConfirmation(input.message, pendingDestructive)) {
      return await destructiveResumeTurn(pendingDestructive, emit, input)
    }

    // A bare "yes"/"confirm" that arrived too late to be trusted. It looks like
    // approval, so silently clearing it and answering something unrelated would
    // leave the caller believing they approved something. Say what was parked
    // and require it to be named — a bare affirmative carries no information
    // about WHICH operation it approves, and the store holds one pending item
    // per project, so over the stateless MCP door it can otherwise resolve an
    // operation parked by a different session entirely.
    const looksAffirmative = isBareAffirmative(input.message)
    await clearPendingDestructive(input.projectId).catch(() => {})

    if (looksAffirmative) {
      const target = describePendingDestructive(pendingDestructive)
      const summary =
        `That confirmation arrived too late to apply safely, so nothing was changed.\n\n` +
        `What was waiting: **${target}**\n\n` +
        `A bare "yes" only resolves a confirmation you just received. Re-state the ` +
        `operation by name if you still want it — e.g. "drop the followers table".`
      emit({ type: 'phase', phase: 'finish' })
      return {
        success: true,
        summary,
        needsUser: true,
        iterations: 0,
        toolsRun,
        classification: {
          intent: 'CONFIRM',
          confidence: 1,
          reasoning: 'Bare affirmative arrived after the confirmation window; nothing was executed.',
        },
        tokensUsed: 0,
      }
    }
  }

  // ── UNDERSTAND ──────────────────────────────────────────────────────────
  emit({ type: 'phase', phase: 'understand' })
  const memory = await loadBrainMemory(input.projectId)
  const understandingBlock = formatUnderstanding(memory.understanding)
  const recent = formatRecentHistory(memory.history, 8)

  // Fresh-project signal — a brand-new project with nothing built yet. Computed
  // BEFORE classification so the classifier can use it: on an empty project a
  // message that describes an app is unambiguously a BUILD, never a
  // clarification. Also used later to route BUILD through the architect and to
  // keep the CONFIRM re-architect fallback from firing on a MODIFY confirm.
  const proof = memory.understanding.proof
  const isFreshProject = !proof || proof.nothingBuilt || (proof.tables?.length ?? 0) === 0

  // ── CLASSIFY ────────────────────────────────────────────────────────────
  emit({ type: 'phase', phase: 'classify' })
  const [hasPendingProposal, hasResumeQueue, hasPendingBlueprint] = await Promise.all([
    hasActiveProposal(input.projectId),
    loadResumeQueue(input.projectId).then(q => q !== null).catch(() => false),
    loadPendingPlan(input.projectId).then(p => p !== null).catch(() => false),
  ])
  const classification = await classify({
    message: input.message,
    recentHistory: recent,
    hasPendingProposal,
    // A pending plan, a pending blueprint, OR an outstanding resume queue
    // all signal the classifier that short imperatives like "continue" /
    // "finish it" / "resume" are CONFIRM, not UNCLEAR. Without this, the
    // classifier defaulted to UNCLEAR ("could you tell me a bit more
    // about 'continue'") and the user burned credits in confused loops.
    hasPendingPlan: hasPendingBlueprint || hasResumeQueue || detectPendingPlan(memory.history),
    // On an empty project, an app description has one meaning: build it. This
    // stops the classifier dead-ending "Users can post recipes and follow
    // each other" in a canned clarification.
    isFreshProject,
  })
  emit({
    type: 'classification',
    intent: classification.intent,
    confidence: classification.confidence,
    reasoning: classification.reasoning,
  })

  console.log(
    `[Brain] project=${input.projectId} msg="${input.message.slice(0, 100)}" intent=${classification.intent} conf=${classification.confidence.toFixed(2)} reason="${classification.reasoning.slice(0, 120)}"`,
  )

  // ── CONFIRM with nothing to confirm ─────────────────────────────────────
  // "yes" / "confirm" is meaningless without something pending. The pending
  // destructive call was already checked and cleared above, and the three
  // other resumable states were loaded before classification, so by here we
  // know there is genuinely nothing to resume.
  //
  // Previously this fell into the full agent loop: it routed, called
  // get_table_schema, kept reasoning, and died on the 90s watchdog with
  // BRAIN_TIMEOUT — a minute and a half of tokens to answer a two-word message
  // that could never have succeeded. Answer immediately instead.
  if (
    classification.intent === 'CONFIRM' &&
    !hasPendingProposal &&
    !hasResumeQueue &&
    !hasPendingBlueprint &&
    !detectPendingPlan(memory.history)
  ) {
    emit({ type: 'phase', phase: 'finish' })
    return {
      success: true,
      summary:
        `There is nothing waiting for confirmation right now, so nothing was changed.\n\n` +
        `If you were approving something from an earlier session, that window has closed — ` +
        `re-state what you want by name and I will do it.`,
      needsUser: true,
      iterations: 0,
      toolsRun,
      classification,
      tokensUsed: 0,
    }
  }

  // ── ROUTE ───────────────────────────────────────────────────────────────
  emit({ type: 'phase', phase: 'route' })

  const dispatchCtx: ToolDispatchContext = {
    projectId: input.projectId,
    userId: input.userId,
    sessionToken: input.sessionToken,
    userMessage: input.message,
    understandingBlock,
    destructiveConfirmed: input.destructiveConfirmed,
    createdThisTurn: new Set<string>(),
    onToolEvent: (e) => {
      if (e.phase === 'start') emit({ type: 'tool_start', tool: e.tool, title: e.title })
      else if (e.phase === 'done') emit({ type: 'tool_done', tool: e.tool, title: e.title, detail: e.detail })
      else emit({ type: 'tool_fail', tool: e.tool, title: e.title, detail: e.detail })
    },
  }

  // CHAT → answer directly, never touch the mutation surface
  if (classification.intent === 'CHAT') {
    console.log(`[Brain] route=CHAT → answer_question (no mutation surface)`)
    return await singleToolTurn('answer_question', { question: input.message }, dispatchCtx, classification, emit, input)
  }

  // UNCLEAR → ask one clarifying question, never build anything.
  if (classification.intent === 'UNCLEAR') {
    // SAFETY NET (the "describe your backend" contract): the classifier is an
    // LLM and occasionally hedges on a perfectly buildable app description. On
    // a brand-new project, if the message actually reads like a product/app
    // description, do NOT dead-end it in a canned clarification — hand it to
    // the architect, whose own vagueness gate asks a *contextual* question if
    // (and only if) the spec genuinely can't be designed. This is what keeps
    // "Users can post recipes and follow each other" from ever getting a
    // "could you tell me a bit more?" reply on a fresh project.
    if (isFreshProject && looksLikeBuildDescription(input.message)) {
      console.log(`[Brain] route=UNCLEAR→ARCHITECT (fresh project + build-shaped description) msg="${input.message.slice(0, 80)}"`)
      const resolved = await resolveBlueprintWithHeartbeat(input.message, input.projectId, emit)
      const buildClass: Classification = {
        intent: 'BUILD',
        confidence: classification.confidence,
        reasoning: 'fresh project + product description — routed to architect (classifier hedged UNCLEAR)',
      }
      if (resolved && 'vague' in resolved && resolved.vague) {
        return await singleToolTurn('ask_user', { question: resolved.askUser, options: [] }, dispatchCtx, buildClass, emit, input)
      }
      if (resolved && 'blueprint' in resolved) {
        return await blueprintProposeTurn(resolved.blueprint, resolved.match, resolved.architectTokens, dispatchCtx, buildClass, emit, input)
      }
      // Architect failed to resolve anything → fall through to a real clarification.
    }
    console.log(`[Brain] route=UNCLEAR → ask_user`)
    const q = await synthesiseClarification(input.message, recent)
    return await singleToolTurn('ask_user', { question: q.question, options: q.options }, dispatchCtx, classification, emit, input)
  }

  // ── BUILD on a fresh project → blueprint propose path ────────────────────
  // This is the structural fix for "the agent ships a toy backend": the LLM
  // is the *creative* layer, the blueprint is the *exhaustiveness* layer.
  //
  //   • Curated keyword hit (social-media, marketplace, saas, chat-app, blog,
  //     project-mgmt) → free, deterministic, hand-crafted.
  //   • Otherwise the LLM architect designs a comprehensive backend for the
  //     user's domain (music streaming, telehealth, ride-share, recipe app,
  //     crypto wallet, language learning, anything they describe). The spec
  //     is validated + enriched and stored as the executable artifact.
  //
  // Either way "go ahead" runs every step deterministically — no LLM
  // re-derivation, no partial coverage, no run_test → fix_backend loop.
  if (classification.intent === 'BUILD' || classification.intent === 'APPLY_PROPOSAL') {
    if (isFreshProject) {
      const resolved = await resolveBlueprintWithHeartbeat(input.message, input.projectId, emit)
      if (resolved && 'vague' in resolved && resolved.vague) {
        console.log(`[Brain] route=ARCHITECT_VAGUE — surfacing clarifying question`)
        return await singleToolTurn('ask_user', { question: resolved.askUser, options: [] }, dispatchCtx, classification, emit, input)
      }
      if (resolved && 'blueprint' in resolved) {
        console.log(
          `[Brain] route=BLUEPRINT_PROPOSE domain=${resolved.match.domain} conf=${resolved.match.confidence.toFixed(2)} ` +
          `matchedOn="${resolved.match.matchedOn}" steps=${resolved.blueprint.steps.length} architectTokens=${resolved.architectTokens}`,
        )
        return await blueprintProposeTurn(resolved.blueprint, resolved.match, resolved.architectTokens, dispatchCtx, classification, emit, input)
      }
    }
  }

  // ── CONFIRM with a pending blueprint plan → deterministic execution ──────
  // Guarded on !destructiveConfirmed: a "Confirm — drop the X table" turn is a
  // DESTRUCTIVE confirmation, never a build confirmation — without this guard
  // a stale pending plan or resume queue would hijack the turn and re-run
  // build steps instead of the drop the user just authorised.
  if (classification.intent === 'CONFIRM' && !input.destructiveConfirmed) {
    const pending = await loadPendingPlan(input.projectId).catch(() => null)
    if (pending) {
      console.log(`[Brain] route=BLUEPRINT_EXECUTE domain=${pending.blueprintDomain} steps=${pending.steps.length} architectTokens=${pending.architectTokens}`)
      return await blueprintExecuteTurn(pending.steps, pending.architectTokens, dispatchCtx, classification, emit, input, pending.blueprintDomain, pending.ledger)
    }

    // No fresh proposal but a resume queue from a partial earlier run → keep
    // going deterministically on the remaining steps. "continue" / "finish it"
    // / "resume" all route here so the user never gets dropped into a
    // confused LLM loop after a partial build. No architect tokens to bill
    // — those were charged on the original proposal/execute pair.
    const resume = await loadResumeQueue(input.projectId).catch(() => null)
    if (resume) {
      console.log(`[Brain] route=BLUEPRINT_RESUME domain=${resume.domain} steps=${resume.steps.length}`)
      return await blueprintExecuteTurn(resume.steps, 0, dispatchCtx, classification, emit, input, resume.domain)
    }

    // No stored plan at all — but the user is confirming/continuing a build.
    // This is the state that produced the endless "continue" loop: the
    // architect had failed on the original turn (e.g. the idle watchdog killed
    // it, or a transient model error), so no pending plan was ever saved, and
    // the build fell into the agent loop — which cannot finish a 40-operation
    // spec in 12 iterations and just re-derives partial work on every retry.
    //
    // Instead of re-entering that loop, re-run the DETERMINISTIC architect on
    // the ORIGINAL build prompt and execute it end-to-end. create_table /
    // generate_api / add_rls / enable_realtime are all idempotent
    // ("CREATE TABLE IF NOT EXISTS", "already exists → success"), so any steps
    // that already landed in a partial run succeed as no-ops, the remaining
    // work is done in one deterministic pass, and the coverage report
    // reconciles against live state. This is what breaks the loop.
    // Guard against re-architecting a MODIFY confirmation ("add reviews to my
    // marketplace" → "go ahead"): those run on a NON-fresh project and are not
    // full-schema specs. We only re-architect when the user gave their own
    // table spec (isExplicitSpec — unambiguously a from-scratch build) or when
    // the project is still empty and the original ask was a substantial build.
    const originalBuild = findOriginalBuildPrompt(memory.history)
    if (originalBuild && (isExplicitSpec(originalBuild) || (isFreshProject && originalBuild.length > 200))) {
      const resolved = await resolveBlueprintWithHeartbeat(originalBuild, input.projectId, emit)
      if (resolved && 'blueprint' in resolved) {
        console.log(
          `[Brain] route=CONFIRM_REARCHITECT domain=${resolved.blueprint.domain} ` +
          `steps=${resolved.blueprint.steps.length} architectTokens=${resolved.architectTokens}`,
        )
        return await blueprintExecuteTurn(
          resolved.blueprint.steps,
          resolved.architectTokens,
          dispatchCtx,
          classification,
          emit,
          input,
          resolved.blueprint.domain,
          extractRequirements(originalBuild),
        )
      }
    }
  }

  // APPLY_PROPOSAL (with no blueprint match) is NOT a dead-end. It enters the
  // agent loop like every other actionable intent. The loop has the
  // conversation history, the apply_proposal tool (for a formal Proposal),
  // AND every build tool — so when no formal Proposal exists it re-derives
  // the items the user is referring to from the recent conversation and
  // builds them directly.
  console.log(`[Brain] route=AGENT_LOOP intent=${classification.intent}`)

  // BUILD / MODIFY / FIX / QUESTION / DESTRUCTIVE / CONFIRM / APPLY_PROPOSAL → agent loop
  return await runAgentLoop(input, classification, memory.summary, understandingBlock, recent, dispatchCtx, emit, toolsRun)
}

/**
 * BLUEPRINT PROPOSE — render the full blueprint as a proposal card AND
 * persist it as the executable pending plan. The next "go ahead" message
 * routes to blueprintExecuteTurn and runs every step deterministically.
 *
 * No LLM round-trip in this path: the blueprint is the source of truth.
 */
async function blueprintProposeTurn(
  blueprint: Blueprint,
  match: BlueprintMatch,
  architectTokens: number,
  ctx: ToolDispatchContext,
  classification: Classification,
  emit: (e: BrainEvent) => void,
  input: BrainInput,
): Promise<BrainResult> {
  // Requirements ledger — extracted from the ORIGINAL prompt now, because the
  // execute turn's message is just "go ahead". Persisted with the plan.
  const ledger = extractRequirements(input.message)

  // Stash the architect token spend on the pending plan so the eventual
  // execute turn — the moment the user actually accepts the build — bills
  // those tokens. Proposing alone is free: the user can still reject it.
  await savePendingPlan(input.projectId, blueprint, match, architectTokens, ledger).catch((err) => {
    console.error('[Brain] savePendingPlan failed (non-fatal):', err)
  })

  // Pre-approval honesty: diff the user's requirements against THIS PLAN so
  // gaps are visible before they type "go ahead" — not discovered after 59
  // steps have already run.
  let coverageBlock = ''
  if (ledgerHasContent(ledger)) {
    const planCoverage = reconcileLedger(ledger, appliedStateFromSteps(blueprint.steps))
    coverageBlock = renderLedgerReport(planCoverage, 'plan')
  }

  // Group steps for a readable proposal card. The blueprint's `steps` are
  // tool-level; the user wants a feature-level summary.
  const groups = groupStepsForProposal(blueprint.steps)
  const lines = [
    `**${blueprint.title}**`,
    '',
    blueprint.summary,
    '',
    ...groups.map((g, i) => `${i + 1}. ${g.label}`),
    ...(coverageBlock ? ['', coverageBlock] : []),
    ...(blueprint.warnings && blueprint.warnings.length
      ? ['', '**Notes**', ...blueprint.warnings]
      : []),
    '',
    'Reply "go ahead" to run this, or tell me what to add or remove.',
  ]

  const summary = lines.join('\n')
  emit({ type: 'final', summary, needsUser: true, data: { kind: 'blueprint_proposal', domain: blueprint.domain, stepCount: blueprint.steps.length } })
  await saveTurn(input.projectId, input.message, summary, input.requestId ?? null)

  return {
    success: true,
    summary,
    needsUser: true,
    iterations: 0,
    toolsRun: ['propose_plan'],
    classification,
    tokensUsed: 0,
  }
}

/** Compress per-tool steps into feature-level bullets for the proposal card. */
function groupStepsForProposal(steps: BlueprintStep[]): Array<{ label: string }> {
  const tables: string[] = []
  const apis: string[] = []
  const rls: string[] = []
  const realtime: string[] = []
  const triggers: string[] = []
  const buckets: string[] = []
  const functions: string[] = []
  const crons: string[] = []
  const seeds: string[] = []
  const other: string[] = []

  for (const s of steps) {
    const t = s.tool
    const tn = (s.args as { tableName?: string }).tableName
    if (t === 'create_table' && tn) tables.push(tn)
    else if (t === 'generate_api' && tn) apis.push(tn)
    else if ((t === 'add_rls' || t === 'set_rls') && tn) rls.push(tn)
    else if (t === 'enable_realtime' && tn) realtime.push(tn)
    else if (t === 'create_trigger' && tn) triggers.push(tn)
    else if (t === 'create_bucket') buckets.push(String((s.args as { bucketName?: string }).bucketName ?? 'media'))
    else if (t === 'generate_function') functions.push(String((s.args as { name?: string }).name ?? 'function'))
    else if (t === 'create_cron_job') crons.push(String((s.args as { schedule?: string }).schedule ?? ''))
    else if (t === 'seed_rows' && tn) seeds.push(tn)
    else if (t === 'enable_auth') other.push('Enable end-user authentication (email + password)')
    else if (t === 'enable_teams') other.push('Wire up team multi-tenancy (orgs + members + invitations)')
    else if (t === 'generate_aggregate_api') other.push(`Aggregate stats endpoint /stats/${String((s.args as { name?: string }).name ?? 'summary')}`)
    else other.push(s.label)
  }

  const groups: Array<{ label: string }> = []
  for (const o of other) groups.push({ label: o })
  if (tables.length) groups.push({ label: `Create ${tables.length} tables: ${tables.join(', ')}` })
  if (apis.length) groups.push({ label: `Generate REST APIs for ${apis.length} tables` })
  if (rls.length) groups.push({ label: `Apply Row-Level Security to ${rls.length} tables (owner + public-read templates)` })
  if (realtime.length) groups.push({ label: `Enable realtime change streaming on ${realtime.length} tables` })
  if (triggers.length) groups.push({ label: `Add notify triggers on ${triggers.length} write-paths` })
  if (functions.length) groups.push({ label: `Create ${functions.length} backend function${functions.length === 1 ? '' : 's'} (automations): ${functions.join(', ')}` })
  if (crons.length) groups.push({ label: `Schedule ${crons.length} recurring job${crons.length === 1 ? '' : 's'} (${crons.join(' · ')})` })
  if (buckets.length) groups.push({ label: `Create storage bucket(s): ${buckets.join(', ')}` })
  if (seeds.length) groups.push({ label: `Seed demo data into ${seeds.length} table${seeds.length === 1 ? '' : 's'}: ${seeds.join(', ')}` })
  return groups
}

/**
 * BLUEPRINT EXECUTE — run every step of a persisted plan deterministically.
 *
 *   • No LLM in the loop — every step's tool + args are already concrete.
 *   • Steps run in order so dependencies (tables → APIs → RLS → realtime →
 *     triggers) resolve cleanly.
 *   • A failure on one step does NOT abort the rest — we keep going and
 *     surface a truthful per-step summary at the end. A funded platform
 *     does not stop at the first hiccup; it reports what landed.
 *   • The pending plan is cleared once execution finishes (success or fail).
 */
async function blueprintExecuteTurn(
  steps: BlueprintStep[],
  architectTokens: number,
  ctx: ToolDispatchContext,
  classification: Classification,
  emit: (e: BrainEvent) => void,
  input: BrainInput,
  domain?: string,
  ledger?: RequirementsLedger,
): Promise<BrainResult> {
  emit({ type: 'phase', phase: 'execute' })

  const succeeded: string[] = []
  const succeededSteps: BlueprintStep[] = []
  const failed: Array<{ label: string; detail: string; step: BlueprintStep }> = []
  const toolsRun: string[] = []
  /** Per-tool outcome aligned by index to `toolsRun` — see the note in the
   *  agent loop: a step that landed is 'applied' even if a sibling step failed,
   *  so Memory never labels applied work with the batch's worst outcome. */
  const toolStatuses: BackendEventStatus[] = []
  /** Tools we actually attempted — both successes and failures count toward billed work. */
  const attemptedTools: string[] = []
  /** Per-table outcomes from the deterministic seed runner. */
  const seedResults: SeedTableResult[] = []
  const seedCtx = createSeedContext(input.projectId)

  for (const step of steps) {
    attemptedTools.push(step.tool)

    // `seed_rows` is a blueprint-executor step, not an LLM tool — route it to
    // the deterministic seed runner (FK + demo-user resolution at insert time).
    if (step.tool === 'seed_rows') {
      const tn = String((step.args as { tableName?: string }).tableName ?? '')
      const rows = Array.isArray((step.args as { rows?: unknown }).rows)
        ? ((step.args as { rows: Array<Record<string, unknown>> }).rows)
        : []
      emit({ type: 'tool_start', tool: 'seed_rows', title: `Seeding demo rows into ${tn}` })
      const r = await runSeedStep(seedCtx, tn, rows)
      seedResults.push(r)
      toolsRun.push(step.tool)
      if (r.inserted === r.requested && r.requested > 0) {
        succeeded.push(step.label)
        succeededSteps.push(step)
        toolStatuses.push('applied')
        emit({ type: 'tool_done', tool: 'seed_rows', title: `Seeded ${r.inserted} rows into ${tn}` })
      } else if (r.inserted > 0) {
        // Partial seeds still count as applied work, but the summary reports
        // the true count — never round a 7/10 up to "done".
        succeeded.push(`${step.label} (${r.inserted}/${r.requested} rows)`)
        succeededSteps.push({ ...step, args: { ...step.args, rows: rows.slice(0, r.inserted) } })
        toolStatuses.push('applied')
        emit({ type: 'tool_done', tool: 'seed_rows', title: `Seeded ${r.inserted}/${r.requested} rows into ${tn}`, detail: r.error })
      } else {
        failed.push({ label: step.label, detail: (r.error ?? 'no rows inserted').slice(0, 200), step })
        toolStatuses.push('failed')
        emit({ type: 'tool_fail', tool: 'seed_rows', title: `Seeding ${tn} failed`, detail: r.error })
      }
      continue
    }

    try {
      const result = await dispatchTool(step.tool as ToolName, step.args, ctx)
      toolsRun.push(step.tool)
      toolStatuses.push(result.ok ? 'applied' : 'failed')
      if (result.ok) {
        succeeded.push(step.label)
        succeededSteps.push(step)
      } else {
        failed.push({ label: step.label, detail: result.summary.slice(0, 200), step })
      }
    } catch (err) {
      failed.push({
        label: step.label,
        detail: err instanceof Error ? err.message.slice(0, 200) : 'unexpected error',
        step,
      })
    }
  }

  // Done — clear the pending plan so a stray future "go ahead" cannot re-fire.
  await clearPendingPlan(input.projectId).catch(() => {})

  // If anything failed, save the failed steps as a resume queue so the user's
  // next "continue" / "finish it" message picks up the remaining work with
  // the same deterministic executor — not a confused LLM loop.
  if (failed.length > 0) {
    await saveResumeQueue(
      input.projectId,
      domain ?? 'custom',
      failed.map(f => f.step),
      `${failed.length} step(s) need a second pass after the first run.`,
    ).catch(() => {})
  } else {
    await clearResumeQueue(input.projectId).catch(() => {})
  }

  emit({ type: 'phase', phase: 'verify' })

  // ── Post-apply verification — run what we built, don't hope ─────────────
  // The behavioral verifier signs up throwaway end-users and exercises the
  // real runtime: auth flow, CRUD lifecycle, RLS cross-user isolation,
  // trigger execution, live HTTP endpoints. The agentic fix loop repairs
  // what it can and re-verifies. Bounded at 2 rounds; failures that survive
  // are reported honestly, never swallowed.
  let verificationBlock = ''
  if (succeededSteps.length > 0) {
    try {
      const { runAgenticFixLoop } = await import('../agentic-fix-loop')
      const fixResult = await runAgenticFixLoop(input.projectId, input.userId, {
        maxRounds: 2,
        emit: (e) => {
          if (e.type === 'fix_loop_verify_start') {
            emit({ type: 'tool_start', tool: 'run_test', title: e.round === 0 ? 'Verifying the live backend' : `Re-verifying (round ${e.round})` })
          } else if (e.type === 'fix_loop_verify_done') {
            emit({
              type: 'tool_done', tool: 'run_test',
              title: e.passed ? 'All runtime checks passed' : `${e.failedChecks.length} runtime check${e.failedChecks.length === 1 ? '' : 's'} failing`,
              detail: e.passed ? undefined : e.failedChecks.map(c => c.name).join(', '),
            })
          } else if (e.type === 'fix_loop_fix_start') {
            emit({ type: 'tool_start', tool: 'fix_backend', title: `Repairing: ${e.fix.reason.slice(0, 80)}` })
          } else if (e.type === 'fix_loop_fix_done') {
            emit({ type: e.success ? 'tool_done' : 'tool_fail', tool: 'fix_backend', title: e.message.slice(0, 100) })
          }
        },
      })
      // Prose summary + the structured evidence fence. The fence rides inside
      // the persisted message, so the chat renders a real evidence card (per
      // check: what was exercised, what came back) on live stream AND refresh.
      const { buildVerificationFence } = await import('../verification-evidence')
      const fence = buildVerificationFence(fixResult)
      verificationBlock = [renderVerificationBlock(fixResult), fence].filter(Boolean).join('\n\n')
    } catch (err) {
      console.error('[Brain] post-build verification failed to run:', err)
      verificationBlock = '**Verification** · could not run this time — say "verify my backend" to run it on demand.'
    }
  }

  const finalProof = await collectProof(input.projectId).catch(() => null)
  const stateBlock = finalProof && !finalProof.nothingBuilt ? formatProof(finalProof) : ''

  // ── Request coverage — reconcile what was ASKED against what EXISTS ─────
  // Ground truth: live proof for tables/auth/realtime/buckets, succeeded plan
  // steps for columns/functions/crons/seeds. Deterministic — no self-grading.
  let coverageBlock = ''
  if (ledger && ledgerHasContent(ledger)) {
    const applied = appliedStateFromSteps(succeededSteps)
    if (finalProof) {
      applied.tables = Array.from(new Set([...applied.tables, ...finalProof.tables]))
      applied.authEnabled = applied.authEnabled || finalProof.authEnabled
      applied.realtimeTables = Array.from(new Set([...applied.realtimeTables, ...finalProof.realtimeTables]))
      applied.buckets = Array.from(new Set([...applied.buckets, ...finalProof.buckets]))
    }
    for (const r of seedResults) {
      if (r.inserted > 0) applied.seededTables.set(r.tableName, r.inserted)
      else applied.seededTables.delete(r.tableName)
    }
    coverageBlock = renderLedgerReport(reconcileLedger(ledger, applied), 'result')
  }

  const summary = [
    failed.length === 0
      ? `**Backend built.** ${succeeded.length} steps applied.`
      : `**${succeeded.length} steps applied.** ${failed.length} item${failed.length === 1 ? '' : 's'} need a follow-up.`,
    ...(coverageBlock ? ['', coverageBlock] : []),
    ...(verificationBlock ? ['', verificationBlock] : []),
    '',
    stateBlock,
    ...(failed.length
      ? ['', `**Follow-ups pending** · ${failed.length}`, ...failed.slice(0, 8).map((f, i) => `${i + 1}. ${f.label}: ${f.detail}`)]
      : []),
    '',
    failed.length === 0
      ? 'Open the dashboard tabs to explore: Database, API Builder, Storage, Realtime, Auth. Reply with what you want to change next.'
      : 'Reply "continue" and I\'ll work the follow-ups one by one.',
  ].filter(Boolean).join('\n')

  emit({ type: 'final', summary, needsUser: false })
  await saveTurn(input.projectId, input.message, summary, input.requestId ?? null)
  await recordBrainOperationalMemory(input, toolsRun, summary, failed.length === 0 ? 'applied' : 'failed', toolStatuses)

  // Bill = architect spend (real, from the propose turn) + per-step proxy
  // for every tool we actually dispatched. We bill attempts (not just
  // successes) because each one ran SQL / codegen / OAuth — the work
  // happened even when the final tool result was `ok=false`. Charging only
  // the green path would let pathological inputs build for free.
  const tokensUsed = architectTokens + proxyTokensForSteps(attemptedTools)

  return {
    success: failed.length === 0,
    summary,
    needsUser: false,
    iterations: steps.length,
    toolsRun,
    classification,
    tokensUsed,
    // The behavioral fix-loop already ran above — tell the route not to run it
    // a second time (see BrainResult.verifiedInline).
    verifiedInline: succeededSteps.length > 0,
  }
}

/**
 * Render the post-build verification outcome. Truthful by construction: the
 * numbers come from the behavioral verifier's final snapshot, and surviving
 * failures are listed by name — never summarized away.
 */
function renderVerificationBlock(result: FixLoopResult): string {
  const checks = result.finalCheckSnapshot?.checks ?? []
  const ran = checks.filter(c => !c.skipped)
  const passed = ran.filter(c => c.passed)
  const failedChecks = ran.filter(c => !c.passed)

  if (ran.length === 0) {
    return '**Verification** · no runtime checks were applicable yet.'
  }

  const repairNote = result.appliedFixes > 0
    ? ` · ${result.appliedFixes} issue${result.appliedFixes === 1 ? '' : 's'} repaired automatically`
    : ''

  if (failedChecks.length === 0) {
    return (
      `**Verified against the live runtime** · ${passed.length}/${ran.length} checks passed${repairNote}\n` +
      `Auth flow, CRUD lifecycle, RLS cross-user isolation, triggers, and live HTTP endpoints were exercised with real requests.`
    )
  }

  return [
    `**Verification** · ${passed.length}/${ran.length} runtime checks passed${repairNote} — ${failedChecks.length} still failing:`,
    ...failedChecks.slice(0, 5).map(c => `• ${c.name}${c.error ? ` — ${c.error.slice(0, 120)}` : ''}`),
    `These are tracked as open findings — say "fix the failing checks" or review them on the dashboard.`,
  ].join('\n')
}

/**
 * Describe a blocked destructive tool for the chat's danger card. Best-effort
 * row count via the workspace-table-stats kernel (cached COUNT — cheap).
 * Honesty rules baked in:
 *   • Structure (tables/columns/buckets) can be rebuilt from a restore point,
 *     but ROW DATA cannot — `reversible` is true only for pure-structure loss.
 *   • The confirm phrase must satisfy the execute route's confirmation gate
 *     (DESTRUCTIVE_CONFIRM_RE or the "Confirm —" prefix rule).
 */
async function describeDanger(
  projectId: string,
  tool: string,
  args: Record<string, unknown>,
): Promise<{ tool: string; target: string; rowCount: number | null; reversible: boolean; confirmPhrase: string }> {
  const str = (k: string): string | null => {
    const v = args[k]
    return typeof v === 'string' && v.trim() ? v.trim() : null
  }
  const tableName = str('tableName') ?? str('table')
  const columnName = str('columnName') ?? str('column')
  const namedThing =
    str('bucketName') ?? str('fileName') ?? str('path') ?? str('name') ??
    str('provider') ?? str('email') ?? str('keyId') ?? str('id')

  // Live row count for table-shaped destruction — cached COUNT, never blocks long.
  let rowCount: number | null = null
  if (tableName && (tool === 'drop_table' || tool === 'truncate_table' || tool === 'drop_column')) {
    try {
      const { getTableStat } = await import('@/lib/services/workspace-table-stats')
      const stat = await getTableStat(projectId, tableName)
      rowCount = stat.rows
    } catch { rowCount = null }
  }

  switch (tool) {
    case 'drop_table':
      return {
        tool,
        target: `the \`${tableName ?? 'unknown'}\` table`,
        rowCount,
        reversible: false, // rows are gone forever; only the empty structure restores
        confirmPhrase: `Confirm — drop the ${tableName ?? ''} table`.trim(),
      }
    case 'truncate_table':
      return {
        tool,
        target: `all rows in \`${tableName ?? 'unknown'}\``,
        rowCount,
        reversible: false,
        confirmPhrase: `Confirm — delete all rows in ${tableName ?? 'the table'}`,
      }
    case 'drop_column':
      return {
        tool,
        target: `column \`${columnName ?? 'unknown'}\` on \`${tableName ?? 'unknown'}\``,
        rowCount,
        reversible: false, // column values are unrecoverable
        confirmPhrase: `Confirm — drop the ${columnName ?? ''} column`.trim(),
      }
    case 'delete_bucket':
      return { tool, target: `the \`${namedThing ?? 'unknown'}\` bucket and every file in it`, rowCount: null, reversible: false, confirmPhrase: `Confirm — delete the ${namedThing ?? ''} bucket`.trim() }
    case 'delete_file':
      return { tool, target: `the file \`${namedThing ?? 'unknown'}\``, rowCount: null, reversible: false, confirmPhrase: 'Confirm — delete the file' }
    case 'disable_realtime':
      return { tool, target: tableName ? `realtime on \`${tableName}\` (live subscribers disconnect)` : 'realtime (live subscribers disconnect)', rowCount: null, reversible: true, confirmPhrase: 'Confirm — disable realtime' }
    case 'trigger_deploy':
      return { tool, target: 'a production deploy', rowCount: null, reversible: true, confirmPhrase: 'Confirm — deploy to production' }
    case 'rollback_deploy':
      return { tool, target: 'a production rollback', rowCount: null, reversible: true, confirmPhrase: 'Confirm — roll back the deploy' }
    case 'revoke_api_key':
      return { tool, target: 'an API key (every client using it stops working immediately)', rowCount: null, reversible: false, confirmPhrase: 'Confirm — revoke the API key' }
    case 'rotate_api_key':
      return { tool, target: 'an API key rotation (the old key stops working immediately)', rowCount: null, reversible: false, confirmPhrase: 'Confirm — rotate the API key' }
    case 'delete_env_var':
      return { tool, target: `the env var \`${namedThing ?? 'unknown'}\` (functions reading it will fail)`, rowCount: null, reversible: false, confirmPhrase: `Confirm — delete the ${namedThing ?? ''} env var`.trim() }
    case 'delete_trigger':
      return { tool, target: `the trigger \`${namedThing ?? 'unknown'}\``, rowCount: null, reversible: false, confirmPhrase: 'Confirm — delete the trigger' }
    case 'delete_ai_function':
      return { tool, target: `the function \`${namedThing ?? 'unknown'}\``, rowCount: null, reversible: false, confirmPhrase: 'Confirm — delete the function' }
    case 'delete_cron_job':
      return { tool, target: `the scheduled job \`${namedThing ?? 'unknown'}\``, rowCount: null, reversible: false, confirmPhrase: 'Confirm — delete the scheduled job' }
    case 'remove_integration_key':
      return { tool, target: `the ${namedThing ?? ''} integration (functions calling it will fail)`.trim(), rowCount: null, reversible: false, confirmPhrase: 'Confirm — disconnect the integration' }
    case 'block_end_user':
      return { tool, target: `the end-user ${namedThing ?? ''} (they lose access immediately)`.trim(), rowCount: null, reversible: true, confirmPhrase: 'Confirm — block the user' }
    case 'remove_permission':
      return { tool, target: 'a row-level security policy (data exposure may widen)', rowCount: null, reversible: true, confirmPhrase: 'Confirm — remove the permission' }
    case 'disable_oauth_provider':
      return { tool, target: `${namedThing ?? 'an OAuth'} sign-in (end-users on this provider cannot log in)`, rowCount: null, reversible: true, confirmPhrase: 'Confirm — disable the provider' }
    default:
      return { tool, target: `\`${tool}\``, rowCount: null, reversible: false, confirmPhrase: `Confirm — run ${tool}` }
  }
}

/** Dispatch one tool and treat its result as the terminal answer. */
async function singleToolTurn(
  tool: ToolName,
  args: Record<string, unknown>,
  ctx: ToolDispatchContext,
  classification: Classification,
  emit: (e: BrainEvent) => void,
  input: BrainInput,
): Promise<BrainResult> {
  const result = await dispatchTool(tool, args, ctx)
  emit({
    type: 'final',
    summary: result.summary,
    needsUser: !!result.needsUser,
    data: result.data,
  })
  // Persist conversation so future turns have context
  await saveTurn(input.projectId, input.message, result.summary, input.requestId ?? null)
  await recordBrainOperationalMemory(input, [tool], result.summary, result.ok ? 'applied' : 'failed')
  // `singleToolTurn` covers two very different shapes:
  //   • Read / chat / clarification tools (answer_question, ask_user,
  //     read_*, get_*, list_*) — no model spend worth billing → 0.
  //   • Direct dispatch of a mutation tool (apply_proposal, generate_function,
  //     fix_backend, etc. — used when the user pre-confirmed and we skip
  //     the agent loop entirely) — these do real internal LLM + DB work,
  //     so bill the proxy. Without this, the same operation through the
  //     deterministic shortcut would be free; through the agent loop
  //     it would cost — a meter the user can game by phrasing differently.
  const tokensUsed = isReadOnlyTool(tool) || CONTROL_TOOLS.has(tool)
    ? 0
    : proxyTokensForSteps([tool])
  return {
    success: result.ok,
    summary: result.summary,
    needsUser: !!result.needsUser,
    iterations: 1,
    toolsRun: [tool],
    classification,
    tokensUsed,
  }
}

/**
 * DESTRUCTIVE RESUME — execute the exact call(s) the danger gate blocked on a
 * previous turn, now that the user has confirmed. Mirrors the MCP Review-Queue
 * approval replay: confirmation is a state transition, not a text-parsing
 * exercise. No classifier, no agent loop — the stored tool+args dispatch
 * verbatim, so nothing (a stale pending plan, a hedging model) can hijack the
 * turn between the user's "yes" and the destruction they authorised.
 */
async function destructiveResumeTurn(
  pending: PendingDestructive,
  emit: (e: BrainEvent) => void,
  input: BrainInput,
): Promise<BrainResult> {
  // Replay mode: the model prose-asked for confirmation without attempting
  // the tool, so there is no concrete call to dispatch. Re-run the ORIGINAL
  // message with destructiveConfirmed=true — the exact replay the MCP Review
  // Queue approval uses. Clear the state FIRST so the recursion cannot loop.
  if (pending.calls.length === 0) {
    console.log(`[Brain] destructive-resume replay original="${pending.originalMessage.slice(0, 100)}"`)
    await clearPendingDestructive(input.projectId).catch(() => {})
    return await runBrain({ ...input, message: pending.originalMessage, destructiveConfirmed: true }, emit)
  }

  emit({ type: 'phase', phase: 'execute' })

  const ctx: ToolDispatchContext = {
    projectId: input.projectId,
    userId: input.userId,
    sessionToken: input.sessionToken,
    userMessage: pending.originalMessage,
    destructiveConfirmed: true,
    createdThisTurn: new Set<string>(),
    onToolEvent: (e) => {
      if (e.phase === 'start') emit({ type: 'tool_start', tool: e.tool, title: e.title })
      else if (e.phase === 'done') emit({ type: 'tool_done', tool: e.tool, title: e.title, detail: e.detail })
      else emit({ type: 'tool_fail', tool: e.tool, title: e.title, detail: e.detail })
    },
  }

  const toolsRun: string[] = []
  const toolStatuses: BackendEventStatus[] = []
  const lines: string[] = []
  let allOk = true
  for (const call of pending.calls) {
    console.log(`[Brain] destructive-resume tool=${call.tool} args=${JSON.stringify(call.args).slice(0, 200)}`)
    const result = await dispatchTool(call.tool as ToolName, call.args, ctx)
    toolsRun.push(call.tool)
    toolStatuses.push(result.ok ? 'applied' : 'failed')
    if (!result.ok) allOk = false
    if (result.summary) lines.push(result.summary)
  }

  // Consumed — a second "yes" must never re-fire the same destruction.
  await clearPendingDestructive(input.projectId).catch(() => {})

  const summary = lines.join('\n\n') || 'Done.'
  emit({ type: 'phase', phase: 'finish' })
  emit({ type: 'final', summary, needsUser: false })
  await saveTurn(input.projectId, input.message, summary, input.requestId ?? null)
  await recordBrainOperationalMemory(input, toolsRun, summary, allOk ? 'applied' : 'failed', toolStatuses)

  return {
    success: allOk,
    summary,
    needsUser: false,
    iterations: pending.calls.length,
    toolsRun,
    classification: {
      intent: 'DESTRUCTIVE',
      confidence: 1,
      reasoning: 'Structured confirm resume — replaying the destructive call blocked on the previous turn.',
    },
    tokensUsed: proxyTokensForSteps(toolsRun),
  }
}

/** Full tool-use loop for build/modify/fix/destructive/question/confirm intents. */
async function runAgentLoop(
  input: BrainInput,
  classification: Classification,
  rolledSummary: string,
  understandingBlock: string,
  recent: Array<{ role: 'user' | 'assistant'; content: string }>,
  ctx: ToolDispatchContext,
  emit: (e: BrainEvent) => void,
  toolsRun: string[],
): Promise<BrainResult> {
  const openai = getOpenAIClient()
  const turnTools = toolsForIntent(classification.intent)

  const intentHint = buildIntentHint(classification.intent)
  const messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = [
    { role: 'system', content: agentSystemPrompt() },
    {
      role: 'system',
      content:
        `${understandingBlock}\n\n` +
        (rolledSummary ? `EARLIER CONTEXT:\n${rolledSummary}\n\n` : '') +
        `INTENT CLASSIFICATION (advisory): ${classification.intent} (${classification.confidence.toFixed(2)}) — ${classification.reasoning}\n` +
        `${intentHint}\n` +
        (input.surface
          ? `USER'S CURRENT PAGE: ${input.surface} — deictic references ("this table", "this page", "why is this failing") likely point at what that section shows. Use it to resolve ambiguity; never refuse because a name was omitted when the page implies it.\n`
          : '') +
        (input.destructiveConfirmed ? 'NOTE: the user has confirmed destructive actions for this turn.' : ''),
    },
  ]
  for (const turn of recent) {
    messages.push({ role: turn.role, content: turn.content })
  }
  messages.push({ role: 'user', content: input.message })

  let mutated = false
  let verifiedAfterMutation = false
  let finalSummary = ''
  let success = false
  let needsUser = false
  let terminalData: unknown = null
  let modelFailed = false
  let modelFailureReason = ''
  let modelFailureCode: BrainFailureCode | undefined
  /** Mutations that landed this turn — reported even if the turn later fails. */
  const appliedMutationTitles: string[] = []
  /**
   * Mutations that were ATTEMPTED and refused, with the reason.
   *
   * Successes were reported and failures were not, so a six-item request where
   * two items were refused came back describing the four that worked — "no
   * error, no warning, no mention". For an additive request that reads as
   * complete, and the caller only discovers the gap when the feature depending
   * on it does not work.
   *
   * A refusal is an OUTCOME of the turn and belongs in its report next to the
   * successes. Kept separate from `applied` rather than merged, because the two
   * answer different questions: what is now true, and what still is not.
   */
  const refusedMutations: Array<{ title: string; reason: string }> = []
  let tokensUsed = 0
  // Per-tool outcome, aligned by index to `toolsRun`. Recorded to Memory so an
  // action that landed reads 'applied' even when a later model call in this
  // same loop times out — the turn-level `success` flag must never smear
  // "failed" across work that actually applied.
  const toolStatuses: BackendEventStatus[] = []
  // Destructive calls the danger gate blocked this turn — persisted so the
  // next affirmative message replays them deterministically (see runBrain's
  // destructive-confirm resume). Without this, confirmation was a stateless
  // regex over the user's next message and the loop could never be escaped
  // by the phrases the model itself suggested.
  const blockedDestructive: PendingDestructiveCall[] = []

  /** Set when the loop stopped to protect its verification reserve. */
  let budgetStopped = false

  let iter = 0
  for (; iter < MAX_ITERATIONS; iter++) {
    // ── Spend the verification reserve BEFORE it can be taken ────────────────
    //
    // Checked at the iteration boundary rather than mid-tool: a model round trip
    // plus a tool can easily be 10-20s, so starting one with less than the
    // reserve left is what guaranteed the run died during verification instead
    // of before it.
    if (input.deadlineAt && Date.now() > input.deadlineAt - VERIFY_RESERVE_MS) {
      budgetStopped = true
      break
    }

    let completion: OpenAI.Chat.Completions.ChatCompletion
    try {
      completion = await callModelWithRetry(openai, messages, turnTools)
    } catch (err) {
      const e = err as any
      console.error('[Brain] model call failed mid-loop (after 1 retry):', {
        status: e?.status,
        code: e?.code,
        type: e?.type,
        message: e instanceof Error ? e.message : String(e),
        iter,
        mutated,
      })
      modelFailed = true
      // Classified ONCE, into prose for the human and a code for the caller.
      // Deriving them separately is how the prose came to say "rate-limited" while
      // the transport reported an unclassified `Brain run failed.`
      if (e?.status === 429 || /rate.?limit/i.test(e?.message ?? '')) {
        modelFailureReason = 'the AI provider rate-limited us'
        modelFailureCode = 'RATE_LIMITED'
      } else if (/timeout|timed out/i.test(e?.message ?? '')) {
        modelFailureReason = 'the AI model timed out'
        modelFailureCode = 'MODEL_TIMEOUT'
      } else {
        modelFailureReason = 'the AI model returned an error'
        modelFailureCode = 'MODEL_ERROR'
      }
      break
    }

    if (input.projectId) trackCompletionCost(completion, input.projectId, 'brain-agent')
    const turnTokens = completion.usage?.total_tokens ?? 0
    tokensUsed += turnTokens
    // Report as spent, not as returned — see BrainInput.onTokens. A caller
    // racing a wall clock only ever sees this.
    if (turnTokens > 0) {
      try { input.onTokens?.(turnTokens) } catch { /* billing must never break the loop */ }
    }

    const choice = completion.choices[0]
    const msg = choice?.message
    if (!msg) break

    if (msg.content?.trim()) {
      emit({ type: 'thinking', text: msg.content.trim().slice(0, 320) })
    }

    const toolCalls = msg.tool_calls ?? []
    if (toolCalls.length === 0) {
      // Model answered without tools — accept its text as the final summary.
      finalSummary = (msg.content ?? '').trim() || 'Done.'
      success = true
      break
    }

    // Record the assistant turn with tool calls before appending results
    messages.push({
      role: 'assistant',
      content: msg.content ?? '',
      tool_calls: toolCalls,
    })

    let finished = false
    for (const call of toolCalls) {
      if (call.type !== 'function') continue
      const toolName = call.function.name as ToolName
      let args: Record<string, unknown> = {}
      try {
        args = call.function.arguments ? JSON.parse(call.function.arguments) : {}
      } catch {
        args = {}
      }

      // Destructive gate — block the tool AND emit a structured danger event
      // so the chat renders a proper approval card (target + live row count +
      // restore-point note) instead of relying on prose alone.
      if (isDestructiveTool(toolName) && !input.destructiveConfirmed) {
        const danger = await describeDanger(input.projectId, toolName, args)
        emit({ type: 'danger', ...danger })
        // Persist the exact blocked call so the next affirmative message
        // ("yes" / the card button / re-stating the same command) replays it
        // deterministically instead of re-deriving through the LLM.
        const dup = blockedDestructive.some(
          (b) => b.tool === toolName && JSON.stringify(b.args) === JSON.stringify(args),
        )
        if (!dup) {
          blockedDestructive.push({ tool: toolName, args, target: danger.target })
          await savePendingDestructive(input.projectId, blockedDestructive, input.message).catch((err) => {
            console.error('[Brain] savePendingDestructive failed (non-fatal):', err)
          })
        }
        messages.push({
          role: 'tool',
          tool_call_id: call.id,
          content: JSON.stringify({
            ok: false,
            blocked: 'needs_confirmation',
            summary:
              `\`${toolName}\` on ${danger.target} is destructive and requires explicit user confirmation` +
              (danger.rowCount !== null ? ` — ${danger.rowCount} live row${danger.rowCount === 1 ? '' : 's'} affected` : '') +
              `. A confirmation card has been shown to the user. Call finish and briefly state what will be lost. ` +
              `If you mention how to confirm, say to press the Confirm button or reply "confirm" — NEVER invent any other phrase or magic words.`,
          }),
        })
        continue
      }

      console.log(`[Brain] tool=${toolName} args=${JSON.stringify(args).slice(0, 200)}`)
      const result = await dispatchTool(toolName, args, ctx)
      toolsRun.push(toolName)
      toolStatuses.push(result.ok ? 'applied' : 'failed')
      console.log(`[Brain] tool=${toolName} ok=${result.ok} terminal=${!!result.terminal} summary="${result.summary.slice(0, 120)}"`)

      // Track verification cadence
      if (toolName === 'read_backend_state' && mutated) verifiedAfterMutation = true
      if (toolName === 'run_test' && mutated) verifiedAfterMutation = true
      // Allowlist-driven: a mutation is anything that is NOT a control tool and
      // NOT a read-only tool. Adding a new read tool to tools.READ_ONLY_TOOLS
      // (or a control tool to CONTROL_TOOLS above) keeps this honest without
      // editing this branch every time.
      const isMutation = !isReadOnlyTool(toolName) && !CONTROL_TOOLS.has(toolName)
      if (isMutation) {
        mutated = true
        // ── A self-verifying tool does not need a verification pass ───────────
        //
        // Verification was a single step at the END of the run, so it was always
        // the step a wall clock cut: four RLS calls in one session all landed and
        // all reported UNVERIFIED. The operation whose correctness matters most
        // was the one that never got confirmed.
        //
        // SELF_VERIFYING tools re-read the catalog INSIDE the executor and refuse
        // to return ok:true if what they read back does not match what they
        // asked for — set_rls compares pg_policies per command and restores the
        // table rather than report a change that is not there. That is a
        // stronger check than the final read_backend_state would have been, and
        // it has already happened by the time we get here. Demanding a second
        // pass afterwards is what pushed the run into the time budget in the
        // first place.
        verifiedAfterMutation = result.ok && SELF_VERIFYING_TOOLS.has(toolName)
        // Recorded even when the turn later fails, so the caller can tell "the
        // run stopped" from "nothing changed" — the distinction that decides
        // whether retrying is safe or duplicates work.
        if (result.ok) appliedMutationTitles.push(humanTitle(toolName, args))
        else refusedMutations.push({
          title: humanTitle(toolName, args),
          reason: (result.summary || 'no reason given').slice(0, 300),
        })
      }

      // Clip hard before feeding back into the loop. Executor summaries can be
      // huge markdown ("## Your Backend Architecture…"); echoing them verbatim
      // every iteration bloats context until the model call times out.
      const clippedSummary =
        result.summary && result.summary.length > 500
          ? result.summary.slice(0, 500) + '…'
          : result.summary
      messages.push({
        role: 'tool',
        tool_call_id: call.id,
        content: JSON.stringify({ ok: result.ok, summary: clippedSummary }),
      })

      if (result.terminal) {
        finalSummary = result.summary || 'Done.'
        needsUser = !!result.needsUser
        terminalData = result.data ?? null
        success = !needsUser && result.ok
        finished = true
      }
    }

    if (finished) {
      // Steer the model to verify if it tried to finish after mutating
      if (mutated && !verifiedAfterMutation && !needsUser) {
        emit({ type: 'phase', phase: 'verify' })
        messages.push({
          role: 'system',
          content:
            'You called finish after mutating state but did not verify. Run ONE verification pass — a single read_backend_state, plus at most one run_test on a new endpoint — then finish again with a truthful summary. Do not test create/list/get separately; one passing call is enough.',
        })
        success = false
        continue
      }
      break
    }

    emit({ type: 'phase', phase: mutated ? 'execute' : 'route' })
  }

  // Truthful failure handling. NEVER claim total failure when work landed —
  // and never call a failure "transient" when we don't know that: name the
  // actual reason so a repeated failure reads as what it is.
  if (modelFailed) {
    const reason = modelFailureReason || 'the AI model returned an error'
    if (mutated) {
      const proof = await collectProof(input.projectId).catch(() => null)
      const state = proof && !proof.nothingBuilt ? formatProof(proof) : ''
      finalSummary =
        `I applied changes, then ${reason} before I could finish verifying. ` +
        'This is the real current state of your backend:\n\n' +
        (state || 'Could not re-read the state. Open the dashboard to confirm.') +
        '\n\nSay "continue" and I\'ll finish and verify the rest. If this keeps happening, wait a minute before retrying.'
      // success stays false (we did not cleanly finish) but the message is honest.
    } else {
      finalSummary =
        `I stopped before changing anything because ${reason}. Nothing was modified. Please try again in a moment.`
    }
    emit({ type: 'error', message: `Recovered from a mid-loop model failure (${reason}) — reported the true state.` })
  }

  // ── The reserved verification pass ─────────────────────────────────────────
  //
  // Deterministic, not model-driven, and that is the point: the step that proves
  // what landed cannot itself be skipped because the model chose a different
  // tool or because a round trip ran long. It reads the live catalog directly.
  let verified = false
  if (budgetStopped) {
    emit({ type: 'phase', phase: 'verify' })
    const proof = await collectProof(input.projectId).catch(() => null)
    verified = !!proof
    const state = proof && !proof.nothingBuilt ? formatProof(proof) : ''
    finalSummary = appliedMutationTitles.length
      ? `I ran out of time budget with work still queued, so I stopped taking new steps and spent the ` +
        `remaining budget VERIFYING what had already landed.\n\n` +
        `Applied and verified (${appliedMutationTitles.length}): ${appliedMutationTitles.join('; ')}.\n\n` +
        (state
          ? `Live state read back from the catalog:\n\n${state}\n\n`
          : `The state read-back itself failed, so treat the list above as applied-but-unconfirmed.\n\n`) +
        (refusedMutations.length
          ? `Attempted and REFUSED (${refusedMutations.length}) — these did NOT take effect:\n` +
            refusedMutations.map((r) => `  • ${r.title} — ${r.reason}`).join('\n') + '\n\n'
          : '') +
        `Nothing else was attempted. Say "continue" for the rest — do NOT replay the whole request, ` +
        `the changes above are already in place.`
      : `I ran out of time budget before changing anything. Nothing was applied. ` +
        `Say "continue" to retry with a fresh budget.` +
        (state ? `\n\nCurrent state, unchanged:\n\n${state}` : '')
    emit({
      type: 'error',
      message:
        `Stopped ${VERIFY_RESERVE_MS / 1000}s before the deadline to guarantee a verification pass — ` +
        `verification is budgeted, never dropped.`,
    })
  }

  if (!finalSummary) {
    finalSummary =
      iter >= MAX_ITERATIONS
        ? "I made progress but ran out of steps before fully finishing. Tell me to continue and I'll pick up where I left off."
        : 'Done.'
  }

  // Prose-ask fallback: a DESTRUCTIVE turn that ended without attempting the
  // tool (the danger gate never fired, so nothing was persisted above). Store
  // a replay marker so the user's next "confirm"/"yes" re-runs THIS message
  // with destructiveConfirmed=true instead of stranding them in an ask-loop.
  if (
    classification.intent === 'DESTRUCTIVE' &&
    !input.destructiveConfirmed &&
    blockedDestructive.length === 0 &&
    !mutated
  ) {
    await savePendingDestructive(input.projectId, [], input.message).catch(() => {})
  }

  emit({ type: 'final', summary: finalSummary, needsUser, data: terminalData })
  await saveTurn(input.projectId, input.message, finalSummary, input.requestId ?? null)
  await recordBrainOperationalMemory(input, toolsRun, finalSummary, success ? 'applied' : 'failed', toolStatuses)

  // ── The failure classification the caller gets ──────────────────────────────
  //
  // Derived from the same facts the summary prose is derived from, so the two can
  // never disagree. `applied` is populated regardless of outcome: a caller must be
  // able to distinguish "the run stopped" from "nothing changed".
  const failureCode: BrainFailureCode | undefined = success
    ? undefined
    : modelFailureCode
      ? modelFailureCode
      : needsUser
        ? 'NEEDS_USER'
        : iter >= MAX_ITERATIONS
          ? 'STEP_BUDGET_EXHAUSTED'
          : toolStatuses.includes('failed')
            ? 'TOOL_REFUSED'
            : undefined

  const RETRYABLE: BrainFailureCode[] = ['RATE_LIMITED', 'MODEL_TIMEOUT', 'MODEL_ERROR']

  return {
    success,
    summary: finalSummary,
    needsUser,
    iterations: iter,
    toolsRun,
    classification,
    tokensUsed,
    ...(failureCode ? { failureCode, retryable: RETRYABLE.includes(failureCode) } : {}),
    applied: appliedMutationTitles,
    // Reported on EVERY path, including a turn that otherwise succeeded. A
    // request whose six items produced four changes and two refusals is not a
    // success with a footnote; the caller has to be told which two.
    ...(refusedMutations.length ? { refused: refusedMutations } : {}),
    ...(budgetStopped ? { budgetStopped: true, verified } : {}),
  }
}

/** ──────────────────────────────────────────────────────────────────────── */

/**
 * Tools removed from the surface when the user is CONFIRMING a plan. Once the
 * user has said "go ahead", offering propose_plan to the model again is the
 * exact bug that made "go ahead" re-emit the same plan instead of running it:
 * with low temperature the model pattern-matches the previous assistant turn
 * and just re-proposes. Removing the tool makes the bug physically impossible.
 *
 * ask_user is kept (execution can still discover a missing credential).
 */
const CONFIRM_TOOL_BLOCKLIST = new Set<string>(['propose_plan'])

function toolsForIntent(intent: BrainIntent): OpenAI.Chat.Completions.ChatCompletionTool[] {
  if (intent !== 'CONFIRM') return BRAIN_TOOLS
  return BRAIN_TOOLS.filter((t) => !CONFIRM_TOOL_BLOCKLIST.has(t.function.name))
}

/**
 * One model call with a single retry on transient failure (timeout / 429 /
 * 5xx / connection reset). A second failure rethrows so the loop can fall
 * back to a truthful summary instead of pretending nothing happened.
 */
async function callModelWithRetry(
  openai: Pick<OpenAI, 'chat'>,
  messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[],
  tools: OpenAI.Chat.Completions.ChatCompletionTool[] = BRAIN_TOOLS,
): Promise<OpenAI.Chat.Completions.ChatCompletion> {
  const params = {
    model: getModel('respond'),
    messages,
    tools,
    tool_choice: 'auto' as const,
    temperature: 0.1,
    max_tokens: 1500,
  }
  // The shared client's 30s timeout is sized for small classify/summarize
  // calls. Agent-loop requests carry 10–20k input tokens (understanding block
  // + conversation + tool transcript) and routinely exceed 30s under load —
  // that timeout is what turned the 2026-07-03 Founder Outreach build into a
  // "model error" loop. 90s per request here; the retry keeps total bounded.
  const perRequest = { timeout: 90_000 }
  try {
    return await openai.chat.completions.create(params, perRequest)
  } catch (err) {
    const e = err as any
    const transient =
      e?.status === 429 ||
      e?.status === 408 ||
      (typeof e?.status === 'number' && e.status >= 500) ||
      e?.code === 'ECONNRESET' ||
      e?.code === 'ETIMEDOUT' ||
      /timeout|timed out/i.test(e?.message ?? '')
    if (!transient) throw err
    console.warn('[Brain] transient model error — retrying once:', e?.status ?? e?.code ?? e?.message)
    await new Promise((r) => setTimeout(r, 1500))
    return await openai.chat.completions.create(params, perRequest)
  }
}

function buildIntentHint(intent: BrainIntent): string {
  switch (intent) {
    case 'BUILD':
      return 'Hint: this is a BUILD request. If it touches 2+ resources or changes >1 subsystem, call propose_plan first. For a single small add, proceed directly.'
    case 'MODIFY':
      return 'Hint: this is a MODIFY request on an existing resource. Use add_column / generate_api / add_rls etc. Do NOT recreate the table.'
    case 'FIX':
      return 'Hint: this is a FIX request. Use read_backend_state to identify what is broken, then fix_backend or a specific mutation. Never destructive without confirmation.'
    case 'DESTRUCTIVE':
      return [
        'Hint: this is a DESTRUCTIVE request. Identify the exact target and CALL the destructive tool now — do NOT ask for confirmation in prose.',
        'An automatic safety gate intercepts unconfirmed destructive calls, shows the user a structured confirmation card (with live row counts), and persists the request so their next "confirm" executes it deterministically.',
        'Prose-asking without calling the tool strands the user in a loop. If the user already confirmed this turn, the gate lets the call through.',
      ].join(' ')
    case 'QUESTION':
      return 'Hint: this is a QUESTION about the project state. Call read_backend_state and then finish with the answer. Do NOT mutate anything.'
    case 'CONFIRM':
      return [
        'Hint: the user has CONFIRMED the plan you proposed in the previous assistant turn (e.g. "go ahead", "yes", "do it").',
        'EXECUTE that plan now — call the actual mutation tools (create_table / generate_api / enable_auth / add_rls / etc.) one by one, then read_backend_state to verify, then finish.',
        'The propose_plan tool is intentionally unavailable on this turn — re-proposing what they just confirmed would loop them forever, so it has been removed from your tool surface.',
        'Do NOT ask the user to confirm again. Do NOT restate the plan as prose. Do the work.',
      ].join(' ')
    case 'APPLY_PROPOSAL':
      return [
        'Hint: the user is telling you to act on a list / set of recommendations / features that came up EARLIER IN THIS CONVERSATION',
        '(e.g. "implement these 3 features", "yes add those", "do all that", "apply all those updates").',
        'Step 1: optionally call apply_proposal once in case a formal Proposal is stored.',
        'Step 2: if apply_proposal returns "No active proposal" (or you did not call it), DO NOT STOP. Read the recent',
        'conversation above, identify the EXACT concrete items the user is referring to (e.g. the features/tables/APIs',
        'you just listed), and BUILD them now with the appropriate tools. Treat it as a BUILD of those items.',
        'Never end the turn with "No active proposal to apply" — that is a failure. The user wants the work done.',
      ].join(' ')
    default:
      return ''
  }
}

/**
 * Produce a contextual clarifying question for a genuinely unclear message.
 *
 * Uses the LLM `clarifyPrompt` (previously written but never wired) so the
 * question adapts to what the user actually said, with 2–3 tappable options.
 * The old implementation string-truncated the message to 80 chars — which is
 * exactly why a clear recipe-app description surfaced as
 * `…and save "?` mid-word. Falls back to a non-truncating generic question
 * only if the model call fails.
 */
async function synthesiseClarification(
  message: string,
  recentHistory: ConversationTurn[],
): Promise<{ question: string; options: string[] }> {
  const fallback = {
    question: 'Just so I get this right — do you want me to build this backend for you, change something that already exists, or answer a question about how Backenly works?',
    options: ['Build it for me', 'Change something existing', 'Answer a question'],
  }
  try {
    const openai = getOpenAIClient()
    const messages: Array<{ role: 'system' | 'user' | 'assistant'; content: string }> = [
      { role: 'system', content: clarifyPrompt() },
    ]
    for (const turn of recentHistory.slice(-4)) {
      messages.push({ role: turn.role, content: turn.content.length > 600 ? turn.content.slice(0, 600) + '…' : turn.content })
    }
    messages.push({ role: 'user', content: message })
    const completion = await openai.chat.completions.create({
      model: getModel('classify'),
      messages,
      temperature: 0.2,
      max_tokens: 160,
      response_format: { type: 'json_object' },
    })
    const raw = completion.choices[0]?.message?.content?.trim() ?? ''
    const parsed = JSON.parse(raw) as { question?: unknown; options?: unknown }
    const question = typeof parsed.question === 'string' && parsed.question.trim() ? parsed.question.trim() : fallback.question
    const options = Array.isArray(parsed.options)
      ? parsed.options.filter((o): o is string => typeof o === 'string' && o.trim().length > 0).slice(0, 3)
      : []
    return { question, options }
  } catch (err) {
    console.error('[Brain] synthesiseClarification LLM call failed — using fallback:', err)
    return fallback
  }
}

async function recordBrainOperationalMemory(
  input: BrainInput,
  tools: string[],
  summary: string,
  status: BackendEventStatus,
  toolStatuses?: BackendEventStatus[],
): Promise<void> {
  if (tools.length === 0) return

  await recordToolExecutionMemory({
    projectId: input.projectId,
    actorId: input.userId,
    userMessage: input.message,
    tools,
    summary,
    status,
    toolStatuses,
  }).catch((error) => {
    console.error('[Operational Memory] Failed to record brain receipt:', error)
  })
}

function detectPendingPlan(history: Array<{ role: 'user' | 'assistant'; content: string }>): boolean {
  for (let i = history.length - 1; i >= 0; i--) {
    const t = history[i]
    if (t.role === 'assistant') {
      return /Reply\s+\*?["']?go ahead["']?\*?\s+to run this/i.test(t.content)
    }
  }
  return false
}

async function hasActiveProposal(projectId: string): Promise<boolean> {
  try {
    const { getActiveProposal } = await import('../proposals/store')
    const p = await getActiveProposal(projectId)
    return p !== null
  } catch {
    return false
  }
}
