/**
 * BRAIN MEMORY
 * ============
 * Single source for what the brain needs to remember across turns:
 *   - conversation history (recent + rolled-up summary)
 *   - a live snapshot of project understanding (what's been built, the user's
 *     stated goal, integrations connected)
 *
 * Reuses existing storage where it already exists (ConversationMessage,
 * BackendGraph, Project). Does not introduce a new memory table.
 */

import { prisma } from '@/lib/db/prisma'
import { loadHistory, saveMessages } from '@/app/api/ai/chat/pipeline/conversation-store'
import { collectProof, type ProofBlock } from '@/lib/ai/proof-system'

export interface ConversationTurn {
  role: 'user' | 'assistant'
  content: string
}

export interface ProjectUnderstanding {
  /** Project display name. */
  projectName: string
  /** User's stated goal — pulled from the project's description, if set. */
  statedGoal: string | null
  /** Live state of the backend (tables/APIs/auth/etc.). */
  proof: ProofBlock | null
  /** Connected integrations (names only, no keys). */
  integrations: string[]
}

export interface BrainMemory {
  history: ConversationTurn[]
  summary: string
  understanding: ProjectUnderstanding
}

/** Load everything the brain needs at the start of a turn. */
export async function loadBrainMemory(projectId: string): Promise<BrainMemory> {
  const [{ history, summaryContext }, project, proof] = await Promise.all([
    loadHistory(projectId).catch(() => ({ history: [], summaryContext: '' })),
    prisma.project.findUnique({
      where: { id: projectId },
      select: { name: true, description: true },
    }),
    collectProof(projectId).catch(() => null),
  ])

  const integrations = await prisma.projectIntegrationKey
    .findMany({
      where: { projectId },
      select: { integrationId: true },
    })
    .then(rows => Array.from(new Set(rows.map(r => r.integrationId))).sort())
    .catch(() => [])

  const turns: ConversationTurn[] = history.map(h => {
    const role: 'user' | 'assistant' = h.role === 'assistant' ? 'assistant' : 'user'
    return { role, content: h.content }
  })
  return {
    history: turns,
    summary: summaryContext || '',
    understanding: {
      projectName: project?.name ?? 'this project',
      statedGoal: project?.description ?? null,
      proof,
      integrations,
    },
  }
}

/**
 * Save one user/assistant exchange to the conversation log.
 *
 * `requestId` is the per-turn idempotency key (UUID generated by the chat
 * client and threaded through the execute route → brain). When the route
 * handler has already persisted the user row with the same requestId,
 * `saveMessages` skips the duplicate user insert; only the ai row lands.
 * Without the key it still writes both — same behaviour as before, just
 * no longer dedup-safe across writers.
 */
export async function saveTurn(
  projectId: string,
  userContent: string,
  aiContent: string,
  requestId?: string | null,
): Promise<void> {
  await saveMessages(projectId, userContent, aiContent, requestId).catch(err => {
    console.error('[BrainMemory] saveTurn failed (non-fatal):', err)
  })
}

/** Format the understanding block for inclusion in the agent system prompt. */
export function formatUnderstanding(u: ProjectUnderstanding): string {
  const lines: string[] = []
  lines.push(`PROJECT: ${u.projectName}`)
  if (u.statedGoal) lines.push(`STATED GOAL: ${u.statedGoal}`)
  if (u.proof) {
    if (u.proof.nothingBuilt) {
      lines.push('BACKEND STATE: nothing has been built yet.')
    } else {
      lines.push('BACKEND STATE:')
      if (u.proof.tables.length) lines.push(`  tables: ${u.proof.tables.join(', ')}`)
      if (u.proof.apis.length)
        lines.push(`  apis: ${u.proof.apis.map(a => a.path).slice(0, 12).join(', ')}${u.proof.apis.length > 12 ? ', …' : ''}`)
      if (u.proof.authEnabled) lines.push(`  auth: enabled (${u.proof.authProviders.join(', ') || 'email'})`)
      if (u.proof.buckets.length) lines.push(`  storage: ${u.proof.buckets.join(', ')}`)
      if (u.proof.rlsPolicies.length) lines.push(`  rls: ${u.proof.rlsPolicies.length} policies`)
      if (u.proof.realtimeTables?.length) lines.push(`  realtime: streaming on ${u.proof.realtimeTables.join(', ')}`)
    }
  } else {
    lines.push('BACKEND STATE: (could not read — call read_backend_state if needed)')
  }
  if (u.integrations.length) lines.push(`CONNECTED INTEGRATIONS: ${u.integrations.join(', ')}`)
  return lines.join('\n')
}

/** Format the recent conversation for inclusion (capped). */
export function formatRecentHistory(
  history: ConversationTurn[],
  max = 8,
): ConversationTurn[] {
  return history.slice(-max).map(t => ({
    role: t.role,
    content: t.content.length > 1500 ? t.content.slice(0, 1500) + '…' : t.content,
  }))
}
