/**
 * Behavioral verifier for @backenly/cli.
 *
 * Boots a stub of the /api/cli/* platform surface, then drives the real CLI
 * binary through link → status → schema → types → diff (clean + drifted) →
 * openapi → logs in a throwaway directory, asserting output and exit codes.
 * No database or Next server required.
 *
 * Run: npx tsx scripts/verify-cli.ts
 */
import http from 'http'
import fs from 'fs'
import os from 'os'
import path from 'path'
import { spawn } from 'child_process'

const ROOT = path.resolve(__dirname, '..')
const CLI = path.join(ROOT, 'packages', 'cli', 'bin', 'backenly.mjs')
const PROJECT_ID = '0e05907b-dab8-4278-87f1-ba792eb01b36'

const DTS = [
  '// Generated by Backenly',
  'export interface PostsRow {',
  '  id: string',
  '  title: string',
  '}',
  'export interface Database { posts: PostsRow }',
].join('\n')

const stub = http.createServer((req, res) => {
  const url = new URL(req.url ?? '/', 'http://x')
  if (url.pathname === '/skill.md') {
    // Public static file in production — no key gate.
    res.writeHead(200, { 'content-type': 'text/markdown' })
    return res.end('# Working with Backenly (for coding agents)\n\ntest skill body\n')
  }
  if (req.headers['x-api-key'] !== 'test-key') {
    res.writeHead(401, { 'content-type': 'application/json' })
    return res.end(JSON.stringify({ ok: false, error: 'Invalid API key' }))
  }
  if (url.pathname === '/api/cli/overview') {
    res.writeHead(200, { 'content-type': 'application/json' })
    return res.end(JSON.stringify({
      ok: true,
      project: { id: PROJECT_ID, name: 'Social Media Backend', environment: 'production', status: 'active', deployed: true, publicEnabled: true },
      schema: {
        generatedAt: new Date().toISOString(),
        tableCount: 1,
        tables: [{ name: 'posts', columns: [
          { name: 'id', type: 'uuid', nullable: false, primaryKey: true },
          { name: 'title', type: 'text', nullable: false },
          { name: 'author_id', type: 'uuid', nullable: false, references: 'profiles.id' },
        ] }],
      },
      counts: { endpoints: 156, functions: 24 },
      apiBase: `https://backenly.com/api/v1/${PROJECT_ID}`,
    }))
  }
  if (url.pathname === '/api/cli/types') {
    const format = url.searchParams.get('format')
    if (format === 'openapi') {
      res.writeHead(200, { 'content-type': 'application/json', 'x-backenly-schema-hash': 'abc123' })
      return res.end(JSON.stringify({ openapi: '3.0.3', info: { title: 'Test API' }, paths: {} }))
    }
    res.writeHead(200, { 'content-type': 'text/plain', 'x-backenly-schema-hash': 'abc123' })
    return res.end(format === 'client' ? '// typed client\nexport const client = 1\n' : DTS)
  }
  if (url.pathname === '/api/cli/query') {
    let raw = ''
    req.on('data', (d) => (raw += d))
    req.on('end', () => {
      const q = JSON.parse(raw || '{}')
      if (/^\s*(update|delete|insert|drop)/i.test(q.sql ?? '')) {
        res.writeHead(422, { 'content-type': 'application/json' })
        return res.end(JSON.stringify({ ok: false, refused: true, code: 'WRITE', error: 'read-only', suggestion: 'run it as a governed change' }))
      }
      res.end(JSON.stringify({ ok: true, rows: [{ id: '1', title: 'A' }], fields: ['id', 'title'], rowCount: 1, capped: false, ms: 3 }))
    })
    return
  }
  if (url.pathname === '/api/cli/logs') {
    res.writeHead(200, { 'content-type': 'application/json' })
    return res.end(JSON.stringify({ ok: true, count: 2, logs: [
      { at: '2026-07-16T10:00:01.000Z', method: 'GET', path: '/posts', status: 200, ms: 6 },
      { at: '2026-07-16T10:00:00.000Z', method: 'POST', path: '/posts', status: 500, ms: 40 },
    ] }))
  }
  res.writeHead(404, { 'content-type': 'application/json' })
  res.end(JSON.stringify({ ok: false, error: 'not found' }))
})

let failures = 0
function check(label: string, ok: boolean, detail?: string) {
  if (!ok) failures++
  console.log(`${ok ? '✔' : '✖'} ${label}${!ok && detail ? ` — ${detail}` : ''}`)
}

// MUST be async: the stub server runs in THIS process, so a spawnSync would
// block the event loop and deadlock the child's HTTP request against it.
function run(
  dir: string,
  args: string[],
  env: Record<string, string> = {},
): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [CLI, ...args], {
      cwd: dir,
      env: { ...process.env, NO_COLOR: '1', ...env },
    })
    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (d) => (stdout += d))
    child.stderr.on('data', (d) => (stderr += d))
    const timer = setTimeout(() => child.kill(), 15_000)
    child.on('close', (status) => {
      clearTimeout(timer)
      resolve({ status, stdout, stderr })
    })
  })
}

async function main() {
  await new Promise<void>((r) => stub.listen(0, '127.0.0.1', r))
  const port = (stub.address() as any).port
  const url = `http://127.0.0.1:${port}`

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'backenly-cli-test-'))
  fs.writeFileSync(path.join(dir, '.gitignore'), 'node_modules/\n')

  // link
  let r = await run(dir, ['link', '--project', PROJECT_ID, '--key', 'test-key', '--url', url])
  check('link succeeds', r.status === 0, r.stderr)
  check('link writes config', fs.existsSync(path.join(dir, '.backenly', 'config.json')))
  check('link gitignores credentials', fs.readFileSync(path.join(dir, '.gitignore'), 'utf8').includes('.backenly/'))

  // link with wrong project id must refuse
  r = await run(dir, ['link', '--project', 'wrong-id', '--key', 'test-key', '--url', url])
  check('link refuses mismatched project', r.status === 1 && r.stderr.includes('belongs to project'))

  // status / schema read config from .backenly/
  r = await run(dir, ['status'])
  check('status renders overview', r.status === 0 && r.stdout.includes('Social Media Backend') && r.stdout.includes('156'))
  r = await run(dir, ['schema'])
  check('schema renders FK graph', r.status === 0 && r.stdout.includes('→ profiles.id'))

  // types
  r = await run(dir, ['types', '--client'])
  check('types writes backenly.types.ts', fs.existsSync(path.join(dir, 'backenly.types.ts')))
  check('types --client writes backenly.client.ts', fs.existsSync(path.join(dir, 'backenly.client.ts')))

  // diff — clean
  r = await run(dir, ['diff'])
  check('diff exits 0 when in sync', r.status === 0, `status=${r.status} ${r.stderr}`)

  // diff — drifted
  fs.appendFileSync(path.join(dir, 'backenly.types.ts'), '\nexport interface StaleRow { gone: true }\n')
  r = await run(dir, ['diff'])
  check('diff exits 1 on drift', r.status === 1 && r.stderr.includes('drift'), `status=${r.status}`)

  // openapi
  r = await run(dir, ['openapi'])
  check('openapi writes spec', r.status === 0 && fs.existsSync(path.join(dir, 'backenly.openapi.json')))

  // logs
  r = await run(dir, ['logs'])
  check('logs renders entries', r.status === 0 && r.stdout.includes('/posts') && r.stdout.includes('500'))

  // query — read-only console
  r = await run(dir, ['query', 'select * from posts limit 1'])
  check('query renders rows', r.status === 0 && r.stdout.includes('title') && r.stdout.includes('read-only'), r.stdout)
  r = await run(dir, ['query', 'delete from posts'])
  check('query surfaces write refusal + funnel', r.status === 1 && r.stderr.includes('governed change'), r.stderr)

  // install-skill (no key required — skill.md is public)
  r = await run(dir, ['install-skill', '--url', url])
  const claudeSkill = path.join(dir, '.claude', 'skills', 'backenly', 'SKILL.md')
  const cursorRule = path.join(dir, '.cursor', 'rules', 'backenly.mdc')
  check('install-skill writes Claude skill', r.status === 0 && fs.existsSync(claudeSkill))
  check('install-skill writes Cursor rule', fs.existsSync(cursorRule))
  check(
    'installed skill carries frontmatter + body',
    fs.existsSync(claudeSkill) &&
      fs.readFileSync(claudeSkill, 'utf8').startsWith('---\nname: backenly') &&
      fs.readFileSync(claudeSkill, 'utf8').includes('test skill body'),
  )

  // auth failure surfaces cleanly
  r = await run(dir, ['status', '--key', 'bad-key', '--url', url])
  check('bad key fails with clear error', r.status === 1 && r.stderr.includes('Invalid API key'))

  // no key + no config
  const bare = fs.mkdtempSync(path.join(os.tmpdir(), 'backenly-cli-bare-'))
  r = await run(bare, ['status'], { BACKENLY_API_KEY: '' })
  check('missing key explains how to link', r.status === 1 && r.stderr.includes('backenly link'))

  fs.rmSync(dir, { recursive: true, force: true })
  fs.rmSync(bare, { recursive: true, force: true })
  await new Promise((r2) => stub.close(r2))

  if (failures > 0) {
    console.error(`\n✖ ${failures} CLI verification(s) failed`)
    process.exitCode = 1
    return
  }
  console.log('\n✔ @backenly/cli verified end-to-end against stub platform')
}

main().catch((e) => {
  console.error(e)
  process.exitCode = 1
})
