export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { setupWorkspaceDatabaseFromSchema } from '@/lib/services/workspaceDatabaseSetup'
import { prisma } from '@/lib/db'
import { withProjectValidation } from '@/lib/middleware/projectValidation'
import { workspaceSchemaName } from '@/lib/security/workspace-schema'

/**
 * POST /api/database/setup-workspace
 * 
 * PRODUCTION-GRADE DATABASE SETUP
 * 
 * This endpoint sets up workspace databases from Prisma schema with:
 * 1. ✅ MANDATORY projectId validation
 * 2. ✅ Project ownership verification
 * 3. ✅ Project-scoped schema paths (no global fallbacks)
 * 4. ✅ Idempotent operation (safe to re-run)
 * 
 * Security:
 * - Uses withProjectValidation middleware for 100% project isolation
 * - Reads schema ONLY from workspace/{projectId}/prisma/schema.prisma
 * - Never accesses other projects' data
 */
export async function POST(request: NextRequest) {
  return withProjectValidation<any>(request, async (validated) => {
    const { projectId, userId, project } = validated
    const requestId = `setup-${Date.now()}`
    
    console.log(`🔵 [${requestId}] === DATABASE SETUP START ===`)
    console.log(`✅ [${requestId}] Project: ${project.name} (${projectId})`)
    console.log(`✅ [${requestId}] User: ${userId}`)

    try {
      // Get-or-create the workspace atomically. A plain findFirst-then-create
      // here is a check-then-create race: two concurrent setup calls both see
      // no workspace and both insert, producing duplicate workspace rows for
      // one project. upsert on the unique projectId is race-safe — the second
      // caller hits the existing row instead of inserting a twin.
      console.log(`📦 [${requestId}] Get-or-create workspace (upsert on projectId)...`)
      const workspace = await prisma.workspace.upsert({
        where: { projectId },
        update: {},
        create: {
          name: `${project.name} Workspace`,
          projectId,
          userId,
          environment: 'development',
          status: 'active',
        },
        select: {
          id: true,
          name: true,
          projectId: true,
          databaseProvisioned: true,
          postgresSchema: true,
          mongodbDatabase: true,
        },
      })

      console.log(`✅ [${requestId}] Workspace ready: ${workspace.id}`)

      console.log(`✅ [${requestId}] Workspace found:`, {
        id: workspace.id,
        name: workspace.name,
        databaseProvisioned: workspace.databaseProvisioned,
        postgresSchema: workspace.postgresSchema,
      })

      // CRITICAL: Use project-scoped schema path ONLY
      // This ensures we never read the wrong project's schema
      const { join } = await import('path')
      const { existsSync, mkdirSync, writeFileSync } = await import('fs')
      const workspaceBase = join(process.cwd(), 'workspace', projectId)
      const schemaPath = join(workspaceBase, 'prisma', 'schema.prisma')
      const envPath = join(workspaceBase, '.env')

      console.log(`🔍 [${requestId}] Schema path: ${schemaPath}`)

      // 🔒 AUTO-CREATE: If schema doesn't exist, create a minimal one (no default tables)
      if (!existsSync(schemaPath)) {
        console.log(`📦 [${requestId}] Prisma schema not found, creating minimal schema...`)
        
        // Create directories if they don't exist
        const prismaDir = join(workspaceBase, 'prisma')
        if (!existsSync(workspaceBase)) {
          mkdirSync(workspaceBase, { recursive: true })
        }
        if (!existsSync(prismaDir)) {
          mkdirSync(prismaDir, { recursive: true })
        }

        // Create minimal Prisma schema WITHOUT any default tables
        const defaultSchema = `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// Your tables will be created here based on your prompts
`

        writeFileSync(schemaPath, defaultSchema, 'utf-8')
        console.log(`✅ [${requestId}] Created minimal Prisma schema (no default tables)`)

        // Create .env file with correct DATABASE_URL
        if (!existsSync(envPath)) {
          const mainDbUrl = process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/backenly_dev'
          // Canonical schema name (hyphens preserved) — must match what the
          // provisioner actually creates. The earlier `replace(/-/g, '_')`
          // wrote a connection URL pointing at a schema that does not exist.
          const workspaceSchema = workspaceSchemaName(projectId)
          const workspaceDbUrl = mainDbUrl.includes('?')
            ? `${mainDbUrl}&schema=${workspaceSchema}`
            : `${mainDbUrl}?schema=${workspaceSchema}`
          
          const envContent = `# Auto-generated by Backenly\nDATABASE_URL="${workspaceDbUrl}"\n`
          writeFileSync(envPath, envContent, 'utf-8')
          console.log(`✅ [${requestId}] Created .env file with workspace DATABASE_URL`)
        }
      }

      console.log(`✅ [${requestId}] Prisma schema found`)

      // Trigger database setup (IDEMPOTENT - safe to re-run)
      console.log(`🚀 [${requestId}] Starting database setup...`)
      const setupResult = await setupWorkspaceDatabaseFromSchema(
        projectId,
        workspace.id,
        schemaPath
      )

      if (setupResult.success) {
        console.log(`✅ [${requestId}] Database setup complete!`)
        return NextResponse.json({
          success: true,
          message: 'Database setup completed successfully!',
          projectId,
          projectName: project.name,
          details: {
            postgresSchema: setupResult.postgresSchema,
            mongodbDatabase: setupResult.mongodbDatabase,
            tablesCreated: setupResult.tablesCreated || [],
            collectionsCreated: setupResult.collectionsCreated || [],
            totalTables: (setupResult.tablesCreated || []).length,
            totalCollections: (setupResult.collectionsCreated || []).length,
          },
        })
      } else {
        console.error(`❌ [${requestId}] Database setup failed:`, setupResult.error)
        return NextResponse.json(
          { 
            error: 'Database setup failed',
            details: setupResult.error,
            projectId,
          },
          { status: 500 }
        )
      }
    } catch (error: any) {
      console.error(`❌ [${requestId}] Error during database setup:`, error)
      return NextResponse.json(
        { 
          error: 'Failed to setup database',
          details: error.message || 'Unknown error',
          projectId,
        },
        { status: 500 }
      )
    }
  })
}
